/**
 * This file is generated by SPP Configurator, do not modify it manually!
 *
 * Customer Info: DIAS Automotive Electronic Systems Co;Ltd.
 *
 * Project Info: AS28 TBox
 *
 * Copyright@2018 SAIC Motor Coporation Limited
 *
 * All Right Reserved
 *
 */

#include "string.h"
#include "sppc_core.h"
#include "sppc_core_types.h"
#include "spp_generated.h"
#include "spp_app.h"
#include "os_log.h"




SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_APN_CFG_REQ_Event_Listener(SPP_DCPD_MSG_TO_MCU_APN_CFG_REQ_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_APN_CFG_REQ_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_IMEI_B004_RESP_Event_Listener(SPP_DCPD_MSG_TO_MCU_IMEI_B004_RESP_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_IMEI_B004_RESP_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_GNSS_Event_Listener(SPP_DCPD_MSG_TO_MCU_GNSS_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_GNSS_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_ICCID_B001_RESP_Event_Listener(SPP_DCPD_MSG_TO_MCU_ICCID_B001_RESP_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_ICCID_B001_RESP_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_NadSta1_B180_RESP_Event_Listener(SPP_DCPD_MSG_TO_MCU_NadSta1_B180_RESP_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_NADSTA1_B180_RESP_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_NadSta2_B181_RESP_Event_Listener(SPP_DCPD_MSG_TO_MCU_NadSta2_B181_RESP_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_NADSTA2_B181_RESP_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_NADIP1_B182_RESP_Event_Listener(SPP_DCPD_MSG_TO_MCU_NADIP1_B182_RESP_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_NADIP1_B182_RESP_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_NADIP2_B183_RESP_Event_Listener(SPP_DCPD_MSG_TO_MCU_NADIP2_B183_RESP_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_NADIP2_B183_RESP_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_RC_OTA_MSG_Event_Listener(SPP_DCPD_MSG_TO_MCU_RC_OTA_MSG_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_RC_OTA_MSG_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_BTC_OTA_MSG_Event_Listener(SPP_DCPD_MSG_TO_MCU_BTC_OTA_MSG_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_BTC_OTA_MSG_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_RC_OTA_TX_RESULT_Event_Listener(SPP_DCPD_MSG_TO_MCU_RC_OTA_TX_RESULT_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_RC_OTA_TX_RESULT_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_BTC_OTA_TX_RESULT_Event_Listener(SPP_DCPD_MSG_TO_MCU_BTC_OTA_TX_RESULT_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_BTC_OTA_TX_RESULT_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_AC_CFG_VER_REQ_Event_Listener(SPP_DCPD_MSG_TO_MCU_AC_CFG_VER_REQ_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_AC_CFG_VER_REQ_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_AC_CFG_SAVE_REQ_Event_Listener(SPP_DCPD_MSG_TO_MCU_AC_CFG_SAVE_REQ_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_AC_CFG_SAVE_REQ_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_VS_DATA_REQ_Event_Listener(SPP_DCPD_MSG_TO_MCU_VS_DATA_REQ_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_VS_DATA_REQ_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_AC_INI_CFG_REQ_Event_Listener(SPP_DCPD_MSG_TO_MCU_AC_INI_CFG_REQ_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_AC_INI_CFG_REQ_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_NAD_SW_VER_B005_RESP_Event_Listener(SPP_DCPD_MSG_TO_MCU_NAD_SW_VER_B005_RESP_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_NAD_SW_VER_B005_RESP_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_NAD_HW_VER_B006_RESP_Event_Listener(SPP_DCPD_MSG_TO_MCU_NAD_HW_VER_B006_RESP_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_NAD_HW_VER_B006_RESP_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_MPUSW_VER_F1B5_RESP_Event_Listener(SPP_DCPD_MSG_TO_MCU_MPUSW_VER_F1B5_RESP_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_MPUSW_VER_F1B5_RESP_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_MPUSUPSW_VER_B000_RESP_Event_Listener(SPP_DCPD_MSG_TO_MCU_MPUSUPSW_VER_B000_RESP_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_MPUSUPSW_VER_B000_RESP_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_RESET_TBOX_Event_Listener(SPP_DCPD_MSG_TO_MCU_RESET_TBOX_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_RESET_TBOX_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_UPDATE_KE_STA_B210_Event_Listener(SPP_DCPD_MSG_TO_MCU_UPDATE_KE_STA_B210_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_UPDATE_KE_STA_B210_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_SAVE_KE_RESULT_Event_Listener(SPP_DCPD_MSG_TO_MCU_SAVE_KE_RESULT_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_SAVE_KE_RESULT_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_IS_SLEEP_READY_Event_Listener(SPP_DCPD_MSG_TO_MCU_IS_SLEEP_READY_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_IS_SLEEP_READY_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_PM_CHANGE_END_Event_Listener(SPP_DCPD_MSG_TO_MCU_PM_CHANGE_END_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_PM_CHANGE_END_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_VERSION_SYNC_Event_Listener(SPP_DCPD_MSG_TO_MCU_VERSION_SYNC_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_VERSION_SYNC_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_SIM_STA_Event_Listener(SPP_DCPD_MSG_TO_MCU_SIM_STA_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_SIM_STA_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_TCALL_CFG_REQ_Event_Listener(SPP_DCPD_MSG_TO_MCU_TCALL_CFG_REQ_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_TCALL_CFG_REQ_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_FOTA_CFG_REQ_Event_Listener(SPP_DCPD_MSG_TO_MCU_FOTA_CFG_REQ_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_FOTA_CFG_REQ_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_FOTA_WAKEUPCAN_REQ_Event_Listener(SPP_DCPD_MSG_TO_MCU_FOTA_WAKEUPCAN_REQ_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_FOTA_WAKEUPCAN_REQ_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_FOTA_CHK_REQ_Event_Listener(SPP_DCPD_MSG_TO_MCU_FOTA_CHK_REQ_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_FOTA_CHK_REQ_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_RDIAG_CHK_REQ_Event_Listener(SPP_DCPD_MSG_TO_MCU_RDIAG_CHK_REQ_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_RDIAG_CHK_REQ_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_RDIAG_REQ_Event_Listener(SPP_DCPD_MSG_TO_MCU_RDIAG_REQ_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_RDIAG_REQ_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_APN_STA_Event_Listener(SPP_DCPD_MSG_TO_MCU_APN_STA_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_APN_STA_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_AC_CERT_UPD_ACK_Event_Listener(SPP_DCPD_MSG_TO_MCU_AC_CERT_UPD_ACK_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_AC_CERT_UPD_ACK_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_AC_CERT_UPD_STA_INFO_Event_Listener(SPP_DCPD_MSG_TO_MCU_AC_CERT_UPD_STA_INFO_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_AC_CERT_UPD_STA_INFO_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_BD_START_STOP_ACK_Event_Listener(SPP_DCPD_MSG_TO_MCU_BD_START_STOP_ACK_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_BD_START_STOP_ACK_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_DIAG_UDISK_UPD_ACK_Event_Listener(SPP_DCPD_MSG_TO_MCU_DIAG_UDISK_UPD_ACK_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_DIAG_UDISK_UPD_ACK_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_DIAG_UDISK_UPD_SAT_Event_Listener(SPP_DCPD_MSG_TO_MCU_DIAG_UDISK_UPD_SAT_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_DIAG_UDISK_UPD_SAT_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_SYS_TIME_REQ_Event_Listener(SPP_DCPD_MSG_TO_MCU_SYS_TIME_REQ_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_SYS_TIME_REQ_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_SYS_TIME_RESP_Event_Listener(SPP_DCPD_MSG_TO_MCU_SYS_TIME_RESP_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_SYS_TIME_RESP_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_RC_OTA_MSG_ACK_Event_Listener(SPP_DCPD_MSG_TO_MCU_RC_OTA_MSG_ACK_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_RC_OTA_MSG_ACK_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_BTC_OTA_MSG_ACK_Event_Listener(SPP_DCPD_MSG_TO_MCU_BTC_OTA_MSG_ACK_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_BTC_OTA_MSG_ACK_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_DTC_REPORT_ACK_Event_Listener(SPP_DCPD_MSG_TO_MCU_DTC_REPORT_ACK_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_DTC_REPORT_ACK_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_START_AC_ACK_Event_Listener(SPP_DCPD_MSG_TO_MCU_START_AC_ACK_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_START_AC_ACK_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_USER_ID_ACK_Event_Listener(SPP_DCPD_MSG_TO_MCU_USER_ID_ACK_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_USER_ID_ACK_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_CLR_ALM_REQ_ACK_Event_Listener(SPP_DCPD_MSG_TO_MCU_CLR_ALM_REQ_ACK_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_CLR_ALM_REQ_ACK_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_ALM_REQ_ACK_Event_Listener(SPP_DCPD_MSG_TO_MCU_ALM_REQ_ACK_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_ALM_REQ_ACK_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_START_RJ_ACK_Event_Listener(SPP_DCPD_MSG_TO_MCU_START_RJ_ACK_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_START_RJ_ACK_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_END_RJ_ACK_Event_Listener(SPP_DCPD_MSG_TO_MCU_END_RJ_ACK_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_END_RJ_ACK_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_AVNSRV_VER_REQ_Event_Listener(SPP_DCPD_MSG_TO_MCU_AVNSRV_VER_REQ_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_AVNSRV_VER_REQ_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_DIAG_FOTA_VER_REQ_Event_Listener(SPP_DCPD_MSG_TO_MCU_DIAG_FOTA_VER_REQ_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_DIAG_FOTA_VER_REQ_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_UPGRADE_ACK_Event_Listener(SPP_DCPD_MSG_TO_MCU_UPGRADE_ACK_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_UPGRADE_ACK_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_ENTER_DEV_MD_RESP_Event_Listener(SPP_DCPD_MSG_TO_MCU_ENTER_DEV_MD_RESP_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_ENTER_DEV_MD_RESP_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_VIN_F190_UPDATE_ACK_Event_Listener(SPP_DCPD_MSG_TO_MCU_VIN_F190_UPDATE_ACK_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_VIN_F190_UPDATE_ACK_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_TSP_IP_C007_ACK_Event_Listener(SPP_DCPD_MSG_TO_MCU_TSP_IP_C007_ACK_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_TSP_IP_C007_ACK_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_TSP_SMS_C008_ACK_Event_Listener(SPP_DCPD_MSG_TO_MCU_TSP_SMS_C008_ACK_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_TSP_SMS_C008_ACK_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_TSP_PORT_C009_ACK_Event_Listener(SPP_DCPD_MSG_TO_MCU_TSP_PORT_C009_ACK_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_TSP_PORT_C009_ACK_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_MPU_RES_GNSS_Event_Listener(SPP_MPU_RES_GNSS_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_MPU_RES_GNSS_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_MPU_RES_WAN_Event_Listener(SPP_MPU_RES_WAN_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_MPU_RES_WAN_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_MPU_RES_UART_Event_Listener(SPP_MPU_RES_UART_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_MPU_RES_UART_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_MPU_RES_PING_Event_Listener(SPP_MPU_RES_PING_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_MPU_RES_PING_EVT, cb);
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_FOTA_FBL_COM_Event_Listener(SPP_DCPD_MSG_TO_MCU_FOTA_FBL_COM_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_FOTA_FBL_COM_EVT, cb);
	return SPP_TRUE;
}
SPP_BOOL SPP_Add_DCPD_MSG_TO_MCU_EOL_CMD_RESP_Event_Listener(SPP_DCPD_MSG_TO_MCU_EOL_CMD_RESP_Callback cb)
{
	sppc_SetListener(SPP_USER_RECV_DCPD_MSG_TO_MCU_EOL_CMD_RESP_EVT, cb);
	return SPP_TRUE;
}



SPP_BOOL SPP_Recv_DCPD_MSG_TO_MCU_VS_DATA_REQ_Event(DcpdPackageToMcuVsReq_t* data)
{
    memset(data,0,sizeof(data));
    data->tHeader.u16EventId = SPP_USER_RECV_DCPD_MSG_TO_MCU_VS_DATA_REQ_EVT;
	return SPP_TRUE;
}

SPP_BOOL SPP_Recv_DCPD_MSG_TO_MCU_BD_START_STOP_ACK_Event(DcpdPackageHeader_t* data)
{
    memset(data,0,sizeof(data));
    data->u16EventId = SPP_USER_RECV_DCPD_MSG_TO_MCU_BD_START_STOP_ACK_EVT;

	return SPP_TRUE;
}

SPP_BOOL SPP_Recv_DCPD_MSG_TO_MCU_CLR_ALM_REQ_ACK_Event(DcpdPackageHeader_t* data)
{
    memset(data,0,sizeof(data));
    data->u16EventId = SPP_USER_RECV_DCPD_MSG_TO_MCU_CLR_ALM_REQ_ACK_EVT;
	return SPP_TRUE;
}


SPP_BOOL SPP_Recv_DCPD_MSG_TO_MCU_ALM_REQ_ACK_Event(DcpdPackageHeader_t* data)
{
    memset(data,0,sizeof(data));
    data->u16EventId = SPP_USER_RECV_DCPD_MSG_TO_MCU_ALM_REQ_ACK_EVT;
	return SPP_TRUE;
}

SPP_BOOL SPP_Recv_DCPD_MSG_TO_MCU_START_RJ_ACK_Event(DcpdPackageHeader_t* data)
{
    memset(data,0,sizeof(data));
    data->u16EventId = SPP_USER_RECV_DCPD_MSG_TO_MCU_START_RJ_ACK_EVT;
	return SPP_TRUE;
}

SPP_BOOL SPP_Recv_DCPD_MSG_TO_MCU_END_RJ_ACK_Event(DcpdPackageHeader_t* data)
{
    memset(data,0,sizeof(data));
    data->u16EventId = SPP_USER_RECV_DCPD_MSG_TO_MCU_END_RJ_ACK_EVT;
	return SPP_TRUE;
}

SPP_STATUS SPP_Recv_DCPD_MSG_TO_MCU_BTC_OTA_MSG_Event(DcpdPackageToMcuBtcOtaMsgRx_t* data)
{
    memset(data,0,sizeof(data));
    data->tHeader.u16EventId = SPP_USER_RECV_DCPD_MSG_TO_MCU_BTC_OTA_MSG_EVT;
	return SPP_FALSE;    
}


SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_APN_CFG_RESP_Event(const DcpdPackageToMpuApnCfg_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_APN_CFG_RESP_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuApnCfg_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_IMEI_B004_REQ_Event(const DcpdPackageHeader_t* data)
{
    (VOID)sppc_AddEvent((UINT16)SPP_USER_SEND_DCPD_MSG_TO_MPU_IMEI_B004_REQ_EVT, (UINT8 *)data, sizeof(DcpdPackageHeader_t));
    return TRUE;
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_ICCID_B001_REQ_Event(const DcpdPackageHeader_t* data)
{
    (VOID)sppc_AddEvent( (UINT16)SPP_USER_SEND_DCPD_MSG_TO_MPU_ICCID_B001_REQ_EVT, (UINT8 *)data, sizeof(DcpdPackageHeader_t));
    return TRUE;
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_NADSTA1_B180_REQ_Event(const DcpdPackageHeader_t* data)
{
    (VOID)sppc_AddEvent( (UINT16)SPP_USER_SEND_DCPD_MSG_TO_MPU_NADSTA1_B180_REQ_EVT, (UINT8 *)data, sizeof(DcpdPackageHeader_t));
    return TRUE;
    
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_NADSTA2_B181_REQ_Event(const DcpdPackageHeader_t* data)
{
    (VOID)sppc_AddEvent( (UINT16)SPP_USER_SEND_DCPD_MSG_TO_MPU_NADSTA2_B181_REQ_EVT, (UINT8 *)data, sizeof(DcpdPackageHeader_t));
    return TRUE;
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_NADIP1_B182_REQ_Event(const DcpdPackageHeader_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_NADIP1_B182_REQ_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageHeader_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_USER_ID_Event(const DcpdPackageToMpuUserId_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_USER_ID_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuUserId_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_NADIP2_B183_REQ_Event(const DcpdPackageHeader_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_NADIP2_B183_REQ_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageHeader_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_RC_OTA_MSG_Event(const DcpdPackageToMpuRcMid3OtaMsgTx_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_RC_OTA_MSG_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuRcMid3OtaMsgTx_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_BTC_OTA_MSG_Event(const DcpdPackageToMpuBtcOtaMsgTx_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_BTC_OTA_MSG_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuBtcOtaMsgTx_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_CA81_UPDATE_Event(const DcpdPackageToMpuBdChnCfgCA81_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_CA81_UPDATE_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuBdChnCfgCA81_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_CF01_UPDATE_Event(const DcpdPackageToMpuBdEventCfgCF01_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_CF01_UPDATE_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuBdEventCfgCF01_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_VIN_F190_UPDATE_Event(const DcpdPackageToMpuVin_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_VIN_F190_UPDATE_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuVin_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_START_AC_Event(const DcpdPackageHeader_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_START_AC_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageHeader_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_AC_CFG_VER_RESP_Event(const DcpdPackageToMpuAcCfgVer_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_AC_CFG_VER_RESP_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuAcCfgVer_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_AC_CFG_SAVE_RESP_Event(const DcpdPackageToMpuAcCfgSaveResult_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_AC_CFG_SAVE_RESP_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuAcCfgSaveResult_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_AC_INI_CFG_RESP_Event(const DcpdPackageToMpuAcCfgIniData_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_AC_INI_CFG_RESP_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuAcCfgIniData_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_TSP_IP_C007_Event(const DcpdPackageToMpuTspIpC007Data_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_TSP_IP_C007_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuTspIpC007Data_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_TSP_SMS_C008_Event(const DcpdPackageToMpuTspSmsC008Data_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_TSP_SMS_C008_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuTspSmsC008Data_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_TSP_PORT_C009_Event(const DcpdPackageToMpuTspPortC009Data_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_TSP_PORT_C009_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuTspPortC009Data_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_TBOX_SN_F18C_Event(const DcpdPackageToMpuTboxSnF18CData_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_TBOX_SN_F18C_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuTboxSnF18CData_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_APP_STA_B200_Event(const DcpdPackageToMpuAppStaB200Data_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_APP_STA_B200_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuAppStaB200Data_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_VS_DATA_RESP_Event(const DcpdPackageToMpuVsData_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_VS_DATA_RESP_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuVsData_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_CLR_ALM_REQ_Event(const DcpdPackageHeader_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_CLR_ALM_REQ_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageHeader_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_ALM_REQ_Event(const DcpdPackageToMpuAlmData_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_ALM_REQ_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuAlmData_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_START_RJ_Event(const DcpdPackageToMpuStartRj_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_START_RJ_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuStartRj_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_UPDTAE_RJ_Event(const DcpdPackageToMpuUpdateRj_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_UPDTAE_RJ_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuUpdateRj_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_END_RJ_Event(const DcpdPackageToMpuEndRj_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_END_RJ_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuEndRj_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_NAD_SW_VER_B005_REQ_Event(const DcpdPackageHeader_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_NAD_SW_VER_B005_REQ_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageHeader_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_NAD_HW_VER_B006_REQ_Event(const DcpdPackageHeader_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_NAD_HW_VER_B006_REQ_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageHeader_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_MPUSW_VER_F1B5_REQ_Event(const DcpdPackageHeader_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_MPUSW_VER_F1B5_REQ_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageHeader_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_MPUSUPSW_VER_B000_REQ_Event(const DcpdPackageHeader_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_MPUSUPSW_VER_B000_REQ_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageHeader_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_TSP_APN_C001_UPDATE_Event(const DcpdPackageToMpuTspApnC001Data_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_TSP_APN_C001_UPDATE_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuTspApnC001Data_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_TSP_APN_USR_C002_UPDATE_Event(const DcpdPackageToMpuTspApnUsrC002Data_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_TSP_APN_USR_C002_UPDATE_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuTspApnUsrC002Data_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_TSP_APN_PSW_C003_UPDATE_Event(const DcpdPackageToMpuTspApnPswC003Data_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_TSP_APN_PSW_C003_UPDATE_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuTspApnPswC003Data_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_INFO_APN_C004_UPDATE_Event(const DcpdPackageToMpuInfoApnC004Data_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_INFO_APN_C004_UPDATE_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuInfoApnC004Data_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_INFO_APN_USR_C005_UPDATE_Event(const DcpdPackageToMpuInfoApnUsrC005Data_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_INFO_APN_USR_C005_UPDATE_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuInfoApnUsrC005Data_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_INFO_APN_PSW_C006_UPDATE_Event(const DcpdPackageToMpuInfoApnPswC006Data_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_INFO_APN_PSW_C006_UPDATE_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuInfoApnPswC006Data_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_VMODEL_C102_UPDATE_Event(const DcpdPackageToMpuVModelC102Data_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_VMODEL_C102_UPDATE_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuVModelC102Data_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_START_KEYEXCHANGE_Event(const DcpdPackageToMpuStartKeyExchange_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_START_KEYEXCHANGE_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuStartKeyExchange_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_KE_SAVE_RESULT_Event(const DcpdPackageToMpuKeSaveResult_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_KE_SAVE_RESULT_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuKeSaveResult_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_PM_STATUS_UPDATE_Event(const DcpdPackageToMpuPmStatusUpdate_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_PM_STATUS_UPDATE_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuPmStatusUpdate_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_SIM_STA_ACK_Event(const DcpdPackageHeader_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_SIM_STA_ACK_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageHeader_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_TCALL_CFG_RESP_Event(const DcpdPackageToMputCallCfg_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_TCALL_CFG_RESP_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMputCallCfg_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_FOTA_CHK_REQ_Event(const DcpdPackageToMpuFotaChkReq_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_FOTA_CHK_REQ_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuFotaChkReq_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_FOTA_CFG_RESP_Event(const DcpdPackageToMpuFotaCfgResp_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_FOTA_CFG_RESP_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuFotaCfgResp_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_FOTA_WAKEUPCAN_RESP_Event(const DcpdPackageToMpuFotaWkpCanNwResp_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_FOTA_WAKEUPCAN_RESP_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuFotaWkpCanNwResp_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_FOTA_CHK_RESP_Event(const DcpdPackageToMpuFotaCondChkResp_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_FOTA_CHK_RESP_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuFotaCondChkResp_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_RDIAG_CHK_RESP_Event(const DcpdPackageToMpuRDiagCondChkResp_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_RDIAG_CHK_RESP_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuRDiagCondChkResp_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_RDIAG_RESP_Event(const DcpdPackageToMpuRDiagResp_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_RDIAG_RESP_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuRDiagResp_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_DTC_REPORT_REQ_Event(const DcpdPackageToMpuDTCReportReq_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_DTC_REPORT_REQ_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuDTCReportReq_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_CERT_UPD_REQ_Event(const DcpdPackageToMpuCertUpdReq_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_CERT_UPD_REQ_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuCertUpdReq_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_AC_CERT_UPD_STA_ACK_Event(const DcpdPackageToMpuCertSaveResult_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_AC_CERT_UPD_STA_ACK_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuCertSaveResult_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_BD_START_STOP_INFO_Event(const DcpdPackageToMpuBdAppStartStopInfo_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_BD_START_STOP_INFO_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuBdAppStartStopInfo_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_BD_EVENT_DATA_Event(const DcpdPackageToMpuBdAppEventData_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_BD_EVENT_DATA_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuBdAppEventData_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_SYS_TIME_RESP_Event(const DcpdPackageToMpuSysTimeOfMcu_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_SYS_TIME_RESP_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuSysTimeOfMcu_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_FOTA_UDISK_UPD_REQ_Event(const DcpdPackageToMpuFotaAppUdiskUpdReq_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_FOTA_UDISK_UPD_REQ_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuFotaAppUdiskUpdReq_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_SYS_TIME_REQ_Event(const DcpdPackageHeader_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_SYS_TIME_REQ_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageHeader_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_RC_OTA_MSG_ACK_Event(const DcpdPackageToMpuRxRcOtaAck_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_RC_OTA_MSG_ACK_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuRxRcOtaAck_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_BTC_OTA_MSG_ACK_Event(const DcpdPackageToMpuRxBtcOtaAck_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_BTC_OTA_MSG_ACK_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuRxBtcOtaAck_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_AVNSRV_VER_RESP_Event(const DcpdPackageToMpuAvnSrvVerResp_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_AVNSRV_VER_RESP_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuAvnSrvVerResp_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_FOTA_KEY_STA_IND_Event(const DcpdPackageToMpuFotaAppKeyStaInd_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_FOTA_KEY_STA_IND_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuFotaAppKeyStaInd_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_FOTA_VER_RESP_Event(const DcpdPackageToMpuFotaVerResp_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_FOTA_VER_RESP_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuFotaVerResp_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_UPGRADE_INFO_Event(const DcpdPackageHeader_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_UPGRADE_INFO_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageHeader_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_RESET_TBOX_ACK_Event(const DcpdPackageHeader_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_RESET_TBOX_ACK_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageHeader_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_ENTER_DEV_MD_REQ_Event(const DcpdPackageHeader_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_ENTER_DEV_MD_REQ_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageHeader_t));
}

SPP_BOOL SPP_Send_MCU_REQ_GNSS_Event(const DcpdPackageHeader_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_MCU_REQ_GNSS_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageHeader_t));
}

SPP_BOOL SPP_Send_MCU_REQ_WAN_Event(const DcpdPackageHeader_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_MCU_REQ_WAN_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageHeader_t));
}

SPP_BOOL SPP_Send_MCU_REQ_UART_Event(const DcpdPackageEolUartInfo_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_MCU_REQ_UART_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageEolUartInfo_t));
}

SPP_BOOL SPP_Send_MCU_REQ_PING_Event(const DcpdPackageHeader_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_MCU_REQ_PING_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageHeader_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_EOL_CMD_REQ_Event(const DcpdPackageToMpuEolCmdReq_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_EOL_CMD_REQ_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageToMpuEolCmdReq_t));
}

SPP_BOOL SPP_Send_DCPD_MSG_TO_MPU_FOTA_FBL_COM_Event(const DcpdPackageFBLCom_t* data)
{
    return sppc_AddEvent(SPP_USER_SEND_DCPD_MSG_TO_MPU_FOTA_FBL_COM_EVT, (SPP_Int8 *)data, sizeof(DcpdPackageFBLCom_t));
}

SPP_BOOL SPP_Init(void)
{
    
    (VOID)DIAS_SPP_Init();
	return SPP_TRUE;
}

SPP_BOOL SPP_Main_Task(void)
{
	(VOID)DIAS_SPP_Main_Task();
    return SPP_TRUE;
}

SPP_BOOL SPP_Start(void)
{
    (VOID)DIAS_SPP_Start();
	return SPP_TRUE;
}

SPP_BOOL SPP_Stop(void)
{
    (VOID)DIAS_SPP_Stop();
	return SPP_TRUE;
}

SPP_BOOL SPP_Sleep(void)
{
    (VOID)DIAS_SPP_Sleep();
	return SPP_TRUE;
}

SPP_BOOL SPP_Wakeup(void)
{
	return SPP_TRUE;
}

SPP_BOOL SPP_SetLogLevel(SPP_LOGLEVEL ll)
{
	return SPP_TRUE;
}

SPP_BOOL SPP_SetLoggingListener(SPP_Logging_Callback cb)
{
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_EventAck_Listener(SPP_UInt16 event_id, SPP_UserEventAck_Callback cb)
{
	return SPP_TRUE;
}

SPP_BOOL SPP_Add_EventAckError_Listener(SPP_UInt16 event_id, SPP_UserEventAckError_Callback cb)
{
	return SPP_TRUE;
}

/******************************************************************************
*  function name | SPP_Add_EventRecv_Listener
*  content       | reserve
*  parameter[1]  | cb :
*  notice        | 
*  return        | 
******************************************************************************/
SPP_BOOL SPP_Add_EventRecv_Listener(SPP_EventRecv_Callback cb)
{
	return SPP_TRUE;
}

SPP_BOOL SPP_TestFlag(SPP_UInt16 event_id)
{
	return SPP_TRUE;
}

void SPP_ClearFlag(SPP_UInt16 event_id)
{
	return ;
}

SPP_BOOL SPP_GetVersionEx(SppVersionEx* spp_version)
{
	SppVersionEx exVis ;
    exVis.sys_version.major = 0;
    exVis.sys_version.minor = 0;
    exVis.sys_version.patch = 0;
    
    exVis.user_version.major = 0;
    exVis.user_version.minor = 0;
    exVis.user_version.patch = 0;

    memset(exVis.md5,0x31,8);
    exVis.md5[8] = 0;
    *spp_version = exVis;
	return SPP_TRUE;
}

SPP_BOOL SPP_GetVersion(SppVersion* spp_version)
{
    spp_version->major = 0;
    spp_version->minor = 0;
    spp_version->patch = 0;

	return SPP_TRUE;
}

SPP_BOOL SPP_DeInit(void)
{
    (VOID)DIAS_SPP_DeInit();
	return SPP_TRUE;
}

SppState_ENUM SPP_GetState(void)
{
    SppState_ENUM e = DIAS_SPP_GetState();
	return e;
}

