/****************************************************************************** 
** Copyright(C) 2021 安徽域驰智能科技有限公司 
**
** File Name:can_config.c
** File Description:
**
**
** File History:
** This file is generated by DCS_Generator, do not modify it manually!
** 2020/7/21       Refer to"S811_CAN Signal List V1.3- 20200515_ICAN.dbc"
**
*******************************************************************************/
#include "system_init.h"
#include "can_driver.h"
#include "can_config.h"
#pragma alignvar(8)
/* DIAG CAN */
 /* Transmitting Frames */ 
UINT8 TxBuffer_0x5F0[8];
UINT8 TxBuffer_0x5F3[8];
UINT8 TxBuffer_0x5F4[8];
UINT8 TxBuffer_0x5F8[8];
UINT8 TxBuffer_0x40D[8];
UINT8 TxBuffer_0x533[8];
UINT8 TxBuffer_0x536[8];
UINT8 TxBuffer_0x5F9[8];
UINT8 TxBuffer_0x5FA[8];
 /* Receiving Frames */ 
UINT8 RxBuffer_0x580[8];
UINT8 RxBuffer_0x583[8];
UINT8 RxBuffer_0x563[8];
UINT8 RxBuffer_0x586[8];
UINT8 RxBuffer_0x515[8];
UINT8 RxBuffer_0x560[8];
UINT8 RxBuffer_0x57D[8];
UINT8 RxBuffer_0x5F7[8];
UINT8 RxBuffer_0x5F5[8];
UINT8 RxBuffer_0x632[8];
UINT8 RxBuffer_0x576[8];
UINT8 RxBuffer_0x578[8];
UINT8 RxBuffer_0x519[8];
UINT8 RxBuffer_0x3F7[8];
UINT8 RxBuffer_0x631[8];
UINT8 RxBuffer_0x56F[8];
UINT8 RxBuffer_0x5F6[8];
UINT8 RxBuffer_0x3B3[8];
UINT8 RxBuffer_0x3B1[8];
UINT8 RxBuffer_0x3BD[8];
UINT8 RxBuffer_0x266[8];
UINT8 RxBuffer_0x23C[8];
UINT8 RxBuffer_0x23D[8];
UINT8 RxBuffer_0x21F[8];
UINT8 RxBuffer_0x32A[8];
UINT8 RxBuffer_0x3CF[8];
UINT8 RxBuffer_0x11A[8];
UINT8 RxBuffer_0x20E[8];
UINT8 RxBuffer_0x247[8];
UINT8 RxBuffer_0x325[8];
UINT8 RxBuffer_0x249[8];
UINT8 RxBuffer_0x117[8];
UINT8 RxBuffer_0x390[8];
UINT8 RxBuffer_0x135[8];
UINT8 RxBuffer_0x525[8];
UINT8 RxBuffer_0x260[8];
UINT8 RxBuffer_0x39A[8];
UINT8 RxBuffer_0x361[8];
UINT8 RxBuffer_0x50A[8];
UINT8 RxBuffer_0x317[8];
UINT8 RxBuffer_0x3A2[8];
UINT8 RxBuffer_0x2AB[8];
UINT8 RxBuffer_0x2CD[8];
UINT8 RxBuffer_0x29A[8];
UINT8 RxBuffer_0x340[8];
UINT8 RxBuffer_0x2C1[8];
UINT8 RxBuffer_0x538[8];
UINT8 RxBuffer_0x53A[8];
UINT8 RxBuffer_0x5A1[8];
UINT8 RxBuffer_0x2D1[8];
UINT8 RxBuffer_0x5A3[8];
UINT8 TxBuffer_0x5A4[8];


/* PT CAN */
  /*rx*/
UINT8 RxBuffer_0x777[8];
UINT8 RxBuffer_0x7DF[8];
UINT8 RxBuffer_0x7E0[8];
UINT8 RxBuffer_0x7E8[8];
UINT8 RxBuffer_0x755[8];
UINT8 RxBuffer_0x75D[8];

UINT8 RxBuffer_0x743[8];
UINT8 RxBuffer_0x74B[8];
UINT8 RxBuffer_0x750[8];
UINT8 RxBuffer_0x758[8];
UINT8 RxBuffer_0x751[8];
UINT8 RxBuffer_0x759[8];
UINT8 RxBuffer_0x752[8];
UINT8 RxBuffer_0x75A[8];
UINT8 RxBuffer_0x754[8];
UINT8 RxBuffer_0x75C[8];
UINT8 RxBuffer_0x756[8];
UINT8 RxBuffer_0x75E[8];
UINT8 RxBuffer_0x765[8];
UINT8 RxBuffer_0x76D[8];
UINT8 RxBuffer_0x766[8];
UINT8 RxBuffer_0x76E[8];
UINT8 RxBuffer_0x767[8];
UINT8 RxBuffer_0x76F[8];
UINT8 RxBuffer_0x770[8];
UINT8 RxBuffer_0x778[8];
UINT8 RxBuffer_0x771[8];
UINT8 RxBuffer_0x779[8];
UINT8 RxBuffer_0x772[8];
UINT8 RxBuffer_0x77A[8];
UINT8 RxBuffer_0x7E1[8];
UINT8 RxBuffer_0x7E9[8];
UINT8 RxBuffer_0x787[8];
UINT8 RxBuffer_0x78F[8];
UINT8 RxBuffer_0x792[8];
UINT8 RxBuffer_0x79A[8];
UINT8 RxBuffer_0x7A0[8];
UINT8 RxBuffer_0x7A8[8];

  /*tx*/
UINT8 TxBuffer_0x77F[8];
UINT8 TxBuffer_0x7E0[8];
UINT8 TxBuffer_0x7DF[8];
UINT8 TxBuffer_0x755[8];

UINT8 TxBuffer_0x743[8];
UINT8 TxBuffer_0x750[8];
UINT8 TxBuffer_0x751[8];
UINT8 TxBuffer_0x752[8];
UINT8 TxBuffer_0x754[8];
UINT8 TxBuffer_0x756[8];
UINT8 TxBuffer_0x765[8];
UINT8 TxBuffer_0x766[8];
UINT8 TxBuffer_0x767[8];
UINT8 TxBuffer_0x770[8];
UINT8 TxBuffer_0x771[8];
UINT8 TxBuffer_0x772[8];
UINT8 TxBuffer_0x7E1[8];
UINT8 TxBuffer_0x787[8];
UINT8 TxBuffer_0x792[8];
UINT8 TxBuffer_0x7A0[8];
UINT8 RxBuffer_NM[8];

/* DIAG Rx Signal Frames */
DCSReceiveSigFrameConfig_t dcs_receiveSigFrameCfg_DIAG[DCS_RxSig_Num_DIAG ] = 
{
    /*  ID,       ID_Mask,    DLC,    RecBuffer,  MsgAddr,        received */
	{ 0x400,     0x1FFFFF00,  0x08,    00,      RxBuffer_NM,    FALSE},
    { 0x580,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x580,    FALSE},
    { 0x583,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x583,    FALSE},
    { 0x563,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x563,    FALSE},
    { 0x586,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x586,    FALSE},
    { 0x515,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x515,    FALSE},
    { 0x560,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x560,    FALSE},
    { 0x57D,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x57D,    FALSE},
    { 0x5F7,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x5F7,    FALSE},
    { 0x5F5,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x5F5,    FALSE},
    { 0x632,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x632,    FALSE},
    { 0x576,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x576,    FALSE},
    { 0x578,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x578,    FALSE},
    { 0x519,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x519,    FALSE},
    { 0x3F7,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x3F7,    FALSE},
    { 0x631,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x631,    FALSE},
    { 0x56F,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x56F,    FALSE},
    
    { 0x3B3,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x3B3,    FALSE},
    { 0x3B1,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x3B1,    FALSE},
    { 0x3BD,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x3BD,    FALSE},
    { 0x266,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x266,    FALSE},
    { 0x23C,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x23C,    FALSE},
    { 0x23D,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x23D,    FALSE},
    { 0x21F,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x21F,    FALSE},
    { 0x32A,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x32A,    FALSE},
    { 0x3CF,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x3CF,    FALSE},
    { 0x11A,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x11A,    FALSE},
    { 0x20E,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x20E,    FALSE},
    { 0x247,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x247,    FALSE},
    { 0x325,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x325,    FALSE},
    { 0x249,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x249,    FALSE},
    { 0x117,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x117,    FALSE},
    { 0x390,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x390,    FALSE},
    { 0x135,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x135,    FALSE},
    { 0x525,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x525,    FALSE},
    { 0x260,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x260,    FALSE},
    { 0x39A,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x39A,    FALSE},
    { 0x361,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x361,    FALSE},
    { 0x50A,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x50A,    FALSE},
    { 0x317,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x317,    FALSE},
    { 0x3A2,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x3A2,    FALSE},
    { 0x2AB,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x2AB,    FALSE},
    { 0x2CD,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x2CD,    FALSE},
    { 0x29A,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x29A,    FALSE},
    { 0x340,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x340,    FALSE},
    { 0x2C1,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x2C1,    FALSE},
    { 0x538,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x538,    FALSE},
    { 0x53A,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x53A,    FALSE},
    { 0x5A1,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x5A1,    FALSE},
    { 0x2D1,     0x1FFFFFFF,  0x08,    00,      RxBuffer_0x2D1,    FALSE},
};
/* DIAG Rx Immediate Frames */
DCSReceiveImFrameConfig_t dcs_receiveImFrameCfg_DIAG[DCS_RxImf_Num_DIAG ] = 
{
	/*  ID,       ID_Mask,    DLC,    RecBuffer,   MsgAddr,      FrameMode Type  */
	{ 0x5A3,  0x1FFFFFFF, 0x08, 50,  RxBuffer_0x5A3,  DCS_RXFMD_APP },
	
	{ 0x5F6,  0x1FFFFFFF, 0x08, 51,  RxBuffer_0x5F6,  DCS_RXFMD_APP},
};

/* DIAG Tx Signal Frames */
DCSTransmitSigFrameConfig_t dcs_TransmitSigFrameCfg_DIAG[DCS_TxSig_Num_DIAG ] = 
{
    /* ID,      DLC,  TrmBuffer,   MsgAddr,            TxType,            updated,  cycle, counter   */
    { 0x5F0,    0x08,   16,       TxBuffer_0x5F0,  DCS_TXTYPE_PERIODIC,    0,          20,    0 },
    { 0x5F3,    0x08,   17,       TxBuffer_0x5F3,  DCS_TXTYPE_PERIODIC,    0,          20,    0 },
    { 0x5F4,    0x08,   18,       TxBuffer_0x5F4,  DCS_TXTYPE_SPORADIC,    0,          0,    0 },
    { 0x5F8,    0x08,   19,       TxBuffer_0x5F8,  DCS_TXTYPE_SPORADIC,    0,          0,    0 },
    { 0x533,    0x08,   20,       TxBuffer_0x533,  DCS_TXTYPE_SPORADIC,    0,          0,    0 },
    { 0x536,    0x08,   21,       TxBuffer_0x536,  DCS_TXTYPE_SPORADIC,    0,          0,    0 },
    { 0x5F9,    0x08,   22,       TxBuffer_0x5F9,  DCS_TXTYPE_SPORADIC,    0,          0,    0 },
    { 0x5FA,    0x08,   23,       TxBuffer_0x5FA,  DCS_TXTYPE_SPORADIC,    0,          0,    0 },
};
/* DIAG Tx Immediate Frames */
DCSTransmitImFrameConfig_t dcs_TransmitImFrameCfg_DIAG[DCS_TxImf_Num_DIAG ] = 
{
    /* ID,      DLC,     TrmBuffer,   MsgAddr,       FrameMode Type*/
    { 0x40D,    0x08,   24,       TxBuffer_0x40D,   DCS_TXFMD_NM },
	{ 0x5A4,    0x08,   25,  	  TxBuffer_0x5A4,   DCS_TXFMD_APP},
};

DCSTransmitImFrameConfig_t dcs_TransmitImFrameCfg_PT[DCS_TxImf_Num_PT ] = 
{
    /* ID,      DLC,     TrmBuffer,   MsgAddr,       FrameMode Type*/
    { 0x77F,    0x08,   0,       TxBuffer_0x77F,   DCS_TXFMD_DIAG },
    { 0x7E0,    0x08,   1,       TxBuffer_0x7E0,   DCS_TXFMD_DIAG },
    { 0x7DF,    0x08,   2,       TxBuffer_0x7DF,   DCS_TXFMD_DIAG },
	{ 0x755,    0x08,   3,       TxBuffer_0x755,   DCS_TXFMD_DIAG },
	{ 0x743,    0x08,   4,       TxBuffer_0x743,   DCS_TXFMD_DIAG },
	{ 0x750,    0x08,   5,       TxBuffer_0x750,   DCS_TXFMD_DIAG },
	{ 0x751,    0x08,   6,       TxBuffer_0x751,   DCS_TXFMD_DIAG },
	{ 0x752,    0x08,   7,       TxBuffer_0x752,   DCS_TXFMD_DIAG },
	{ 0x754,    0x08,   8,       TxBuffer_0x754,   DCS_TXFMD_DIAG },
	{ 0x756,    0x08,   9,       TxBuffer_0x756,   DCS_TXFMD_DIAG },
	{ 0x765,    0x08,   10,       TxBuffer_0x765,   DCS_TXFMD_DIAG },
	{ 0x766,    0x08,   11,       TxBuffer_0x766,   DCS_TXFMD_DIAG },
	{ 0x767,    0x08,   12,       TxBuffer_0x767,   DCS_TXFMD_DIAG },
	{ 0x770,    0x08,   13,       TxBuffer_0x770,   DCS_TXFMD_DIAG },
	{ 0x771,    0x08,   14,       TxBuffer_0x771,   DCS_TXFMD_DIAG },
	{ 0x772,    0x08,   15,       TxBuffer_0x772,   DCS_TXFMD_DIAG },
	{ 0x7E1,    0x08,   16,       TxBuffer_0x7E1,   DCS_TXFMD_DIAG },
	{ 0x787,    0x08,   17,       TxBuffer_0x787,   DCS_TXFMD_DIAG },
	{ 0x792,    0x08,   18,       TxBuffer_0x792,   DCS_TXFMD_DIAG },
	{ 0x7A0,    0x08,   19,       TxBuffer_0x7A0,   DCS_TXFMD_DIAG },
};


DCSReceiveSigFrameConfig_t dcs_receiveSigFrameCfg_PT[DCS_RxSig_Num_PT ] = 
{
    /*  ID,       ID_Mask,    DLC,    RecBuffer,  MsgAddr,        received */
	{ 0x777,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x777,  FALSE },
    { 0x7DF,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x7DF,  FALSE },
    { 0x7E0,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x7E0,  FALSE },
    { 0x7E8,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x7E8,  FALSE },
	{ 0x755,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x755,  FALSE },
	{ 0x75D,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x75D,  FALSE },

	{ 0x743,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x743,  FALSE },
	{ 0x74B,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x74B,  FALSE },
	{ 0x750,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x750,  FALSE },
	{ 0x758,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x758,  FALSE },
	{ 0x751,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x751,  FALSE },
	{ 0x759,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x759,  FALSE },
	{ 0x752,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x752,  FALSE },
	{ 0x75A,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x75A,  FALSE },
	{ 0x754,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x754,  FALSE },
	{ 0x75C,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x75C,  FALSE },
	{ 0x756,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x756,  FALSE },
	{ 0x75E,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x75E,  FALSE },
	{ 0x765,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x765,  FALSE },
	{ 0x76D,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x76D,  FALSE },
	{ 0x766,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x766,  FALSE },
	{ 0x76E,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x76E,  FALSE },
	{ 0x767,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x767,  FALSE },
	{ 0x76F,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x76F,  FALSE },
	{ 0x770,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x770,  FALSE },
	{ 0x778,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x778,  FALSE },
	{ 0x771,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x771,  FALSE },
	{ 0x779,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x779,  FALSE },
	{ 0x772,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x772,  FALSE },
	{ 0x77A,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x77A,  FALSE },
	{ 0x7E1,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x7E1,  FALSE },
	{ 0x7E9,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x7E9,  FALSE },
	{ 0x787,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x787,  FALSE },
	{ 0x78F,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x78F,  FALSE },
	{ 0x792,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x792,  FALSE },
	{ 0x79A,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x79A,  FALSE },
	{ 0x7A0,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x7A0,  FALSE },
	{ 0x7A8,  0x1FFFFFFF, 0x08, 00,  RxBuffer_0x7A8,  FALSE },
};

/* DIAG OSEK RX Frames */
DCSOSEKNMRxFrameConfig_t dcs_OSEKNM_RxframeCfg_DIAG = 
{
    /*  ID,       ID_Mask,    DLC,    FIFOBuffer   */
     0x000,    0x0000,   0x08,        0x03,DCS_RxSig_Num_DIAG,
};

DCSOSEKNMRxFrameConfig_t dcs_OSEKNM_RxframeCfg_PT = 
{
    /*  ID,       ID_Mask,    DLC,    FIFOBuffer   */
     0x000,    0x0000,   0x08,        0x00,DCS_RxSig_Num_PT,
};


const DCS_controllerConfig  dcs_controllConfig_DIAG =
{
    1,              /* channel      */
    0,              /* SJW      */ 
    2,              /* TESG2      */ 
    11,              /* TESG1      */ 
    1,              /* BRP      */
    BYTE_ORDER_MOT, /* byte order */
    DCS_TxSig_Num_DIAG,
    DCS_TxImf_Num_DIAG,
    0,
    DCS_RxImf_Num_DIAG,


    dcs_receiveSigFrameCfg_DIAG, /* RX Sig */
    dcs_receiveImFrameCfg_DIAG,  /* RX Imf */
    dcs_TransmitSigFrameCfg_DIAG,  /* TX Sig */
    dcs_TransmitImFrameCfg_DIAG,  /* TX Imf */
    &dcs_OSEKNM_RxframeCfg_DIAG, /* OSEK NM */
};

const DCS_controllerConfig  dcs_controllConfig_PT =
{
    0,              /* channel      */
    0,              /* SJW      */ 
    2,              /* TESG2      */ 
    11,              /* TESG1      */ 
    1,              /* BRP      */
    BYTE_ORDER_MOT, /* byte order */
    0,
    DCS_TxImf_Num_PT,
    0,
    DCS_RxImf_Num_PT,


    dcs_receiveSigFrameCfg_PT, /* RX Sig */
    NULL,  /* RX Imf */
    NULL,  /* TX Sig */
    dcs_TransmitImFrameCfg_PT,  /* TX Imf */
    &dcs_OSEKNM_RxframeCfg_PT, /* OSEK NM */
};
    


const DCSSignalConfig_t dcs_all_signals[DCS_Signal_Num] =
{
    /* Signal Enum                                  Frame Buffer   start_bit len  update  signal type  */
	{  GPSTimeYear,                                RxBuffer_0x580 ,  	12	, 12  , 0 ,BYTE_ORDER_MOT},
	{  GPSTimeMonth,                               RxBuffer_0x580 ,  	8	, 4   , 0 ,BYTE_ORDER_MOT},
	{  GPSTimeDay,                                 RxBuffer_0x580 ,  	16	, 5   , 0 ,BYTE_ORDER_MOT},
	{  GPSTimeHour,                                RxBuffer_0x580 ,  	24	, 5   , 0 ,BYTE_ORDER_MOT},
	{  GPSTimeMinute,                              RxBuffer_0x580 ,  	32	, 6   , 0 ,BYTE_ORDER_MOT},
	{  GPSTimeSecond,                              RxBuffer_0x580 ,  	40	, 6   , 0 ,BYTE_ORDER_MOT},
	{  GPSTimeStatus,                              RxBuffer_0x580 ,  	46	, 2   , 0 ,BYTE_ORDER_MOT},
	{  TimeDisplayFormat,                          RxBuffer_0x580 ,  	48	, 2   , 0 ,BYTE_ORDER_MOT},
	{  LightDelayOutSet,                           RxBuffer_0x583 ,  	0 	, 3   , 0 ,BYTE_ORDER_MOT},
	{  LightDelayInSet,                            RxBuffer_0x583 ,  	3 	, 3   , 0 ,BYTE_ORDER_MOT},
	{  LightPostonAvailableSet,                    RxBuffer_0x583 ,  	6 	, 2   , 0 ,BYTE_ORDER_MOT},
	{  HU_BackLightLvl,                            RxBuffer_0x583 ,  	8	, 8   , 0 ,BYTE_ORDER_MOT},
	{  HornAlertVolumeSet,                         RxBuffer_0x583 ,  	17	, 2   , 0 ,BYTE_ORDER_MOT},
	{  FloorLightDelayInSet,                       RxBuffer_0x583 ,  	19	, 2   , 0 ,BYTE_ORDER_MOT},
	{  SpeedLockValueSet,                          RxBuffer_0x583 ,  	21	, 2   , 0 ,BYTE_ORDER_MOT},
	{  WindowRemoteAutoDownStateSet,               RxBuffer_0x583 ,  	23	, 1   , 0 ,BYTE_ORDER_MOT},
	{  AssistIlluminationStateSet,                 RxBuffer_0x583 ,  	25	, 1   , 0 ,BYTE_ORDER_MOT},
	{  AutoRainCloseWndEnableSet,                  RxBuffer_0x583 ,  	27	, 1   , 0 ,BYTE_ORDER_MOT},
	{  AutoWiperEnableSet,                         RxBuffer_0x583 ,  	28	, 1   , 0 ,BYTE_ORDER_MOT},
	{  CSS_SwitchEnalblesig,                       RxBuffer_0x583 ,  	29	, 1   , 0 ,BYTE_ORDER_MOT},
	{  PDC_SWSet,                                  RxBuffer_0x583 ,  	30	, 2   , 0 ,BYTE_ORDER_MOT},
	{  RearviewMirrorAvailableSet,                 RxBuffer_0x583 ,  	32	, 1   , 0 ,BYTE_ORDER_MOT},
	{  RMBackDownSet,                              RxBuffer_0x583 ,  	33	, 1   , 0 ,BYTE_ORDER_MOT},
	{  BSD_FUNCTION_SW,                            RxBuffer_0x583 ,  	40	, 1   , 0 ,BYTE_ORDER_MOT},
	{  RGearAutoWiperSet,                          RxBuffer_0x583 ,  	48	, 1   , 0 ,BYTE_ORDER_MOT},
	{  PLG_HMI_Set,                                RxBuffer_0x583 ,  	49	, 3   , 0 ,BYTE_ORDER_MOT},
	{  CTA_SWSet,                                  RxBuffer_0x583 ,  	52	, 1   , 0 ,BYTE_ORDER_MOT},
	{  BSD_LCMA_SW_Set,                            RxBuffer_0x583 ,  	53	, 1   , 0 ,BYTE_ORDER_MOT},
	{  RCW_SWSet,                                  RxBuffer_0x583 ,  	54	, 1   , 0 ,BYTE_ORDER_MOT},
	{  PW_SWSet,                                   RxBuffer_0x583 ,  	55	, 1   , 0 ,BYTE_ORDER_MOT},
	{  WiperVoiceCtrl,                             RxBuffer_0x583 ,  	57	, 2   , 0 ,BYTE_ORDER_MOT},
	{  WLC_SW,                                     RxBuffer_0x583 ,  	59	, 1   , 0 ,BYTE_ORDER_MOT},
	{  WLC_ModuleOff_0x583,                        RxBuffer_0x583 ,  	61	, 1   , 0 ,BYTE_ORDER_MOT},
	{  Wiper_Voice_controlSET,                     RxBuffer_0x583 ,  	63	, 1   , 0 ,BYTE_ORDER_MOT},
	{  MP5Status,                                  RxBuffer_0x563 ,  	0 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  HUACDisplayState,                           RxBuffer_0x563 ,  	4 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  PageSelectButton,                           RxBuffer_0x563 ,  	8 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  HU_TBOX_WiFiRequest,                        RxBuffer_0x563 ,  	10	, 1   , 0 ,BYTE_ORDER_MOT},
	{  HU_TBOX_SNRequest,                          RxBuffer_0x563 ,  	11	, 1   , 0 ,BYTE_ORDER_MOT},
	{  HU_TBOX_VINRequest,                         RxBuffer_0x563 ,  	12	, 1   , 0 ,BYTE_ORDER_MOT},
	{  AsteriskButton,                             RxBuffer_0x563 ,  	14	, 2   , 0 ,BYTE_ORDER_MOT},
	{  AsteriskSet,                                RxBuffer_0x563 ,  	16	, 3   , 0 ,BYTE_ORDER_MOT},
	{  Mp5ResetTboxRequest,                        RxBuffer_0x563 ,  	19	, 1   , 0 ,BYTE_ORDER_MOT},
	{  Mp5WifiRequest,                        	   RxBuffer_0x563 ,  	24	, 2   , 0 ,BYTE_ORDER_MOT},
	{  HU_Xcoordinate,                             RxBuffer_0x586 ,  	8 	, 16  , 0 ,BYTE_ORDER_MOT},
	{  HU_Ycoordinate,                             RxBuffer_0x586 ,  	24	, 16  , 0 ,BYTE_ORDER_MOT},
	{  HU_CoTouchmotion,                           RxBuffer_0x586 ,  	33	, 1   , 0 ,BYTE_ORDER_MOT},
	{  APASW,                                      RxBuffer_0x586 ,  	56	, 1   , 0 ,BYTE_ORDER_MOT},
	{  AVMSW,                                      RxBuffer_0x586 ,  	57	, 1   , 0 ,BYTE_ORDER_MOT},
	{  SteeringModeSet,                            RxBuffer_0x515 ,  	8 	, 2   , 0 ,BYTE_ORDER_MOT},
	{  LDW_SWSet,                                  RxBuffer_0x515 ,  	12	, 1   , 0 ,BYTE_ORDER_MOT},
	{  FCWSet,                                     RxBuffer_0x515 ,  	13	, 1   , 0 ,BYTE_ORDER_MOT},
	{  AEBSet,                                     RxBuffer_0x515 ,  	14	, 1   , 0 ,BYTE_ORDER_MOT},
	{  ADASSensitivitySet,                         RxBuffer_0x515 ,  	16	, 2   , 0 ,BYTE_ORDER_MOT},
	{  HMASwitchSet,                               RxBuffer_0x515 ,  	18	, 1   , 0 ,BYTE_ORDER_MOT},
	{  LKASSet,                                    RxBuffer_0x515 ,  	19	, 1   , 0 ,BYTE_ORDER_MOT},
	{  SLASwitch,                                  RxBuffer_0x515 ,  	20	, 1   , 0 ,BYTE_ORDER_MOT},
	{  NavSpeedLimitStatus,                        RxBuffer_0x515 ,  	22	, 2   , 0 ,BYTE_ORDER_MOT},
	{  NavCountryCode,                             RxBuffer_0x515 ,  	24	, 8   , 0 ,BYTE_ORDER_MOT},
	{  NavSpeedLimit,                              RxBuffer_0x515 ,  	32	, 6   , 0 ,BYTE_ORDER_MOT},
	{  NavCurrRoadType,                            RxBuffer_0x515 ,  	40	, 4   , 0 ,BYTE_ORDER_MOT},
	{  FCWSensiSet,                                RxBuffer_0x515 ,  	44	, 2   , 0 ,BYTE_ORDER_MOT},
	{  WL_Position_Req_FL,                         RxBuffer_0x560 ,  	0 	, 4   , 0 ,BYTE_ORDER_MOT},
	{  WL_Position_Req_FR,                         RxBuffer_0x560 ,  	4 	, 4   , 0 ,BYTE_ORDER_MOT},
	{  WL_Position_Req_RL,                         RxBuffer_0x560 ,  	8	, 4   , 0 ,BYTE_ORDER_MOT},
	{  WL_Position_Req_RR,                         RxBuffer_0x560 ,  	12	, 4   , 0 ,BYTE_ORDER_MOT},
	{  ALLWindowstop_Req,                          RxBuffer_0x560 ,  	16	, 1   , 0 ,BYTE_ORDER_MOT},
	{  HU_FLSeatHeat,                              RxBuffer_0x560 ,  	24	, 3   , 0 ,BYTE_ORDER_MOT},
	{  HU_FRSeatHeat,                              RxBuffer_0x560 ,  	28	, 3   , 0 ,BYTE_ORDER_MOT},
	{  SeatGreeterSet,                             RxBuffer_0x560 ,  	31	, 1   , 0 ,BYTE_ORDER_MOT},
	{  Sunroof_VoiceCmd,                           RxBuffer_0x560 ,  	40	, 4   , 0 ,BYTE_ORDER_MOT},
	{  AL01_Authorization,                         RxBuffer_0x57D ,  	0 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  AL02_Authorization,                         RxBuffer_0x57D ,  	1 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  AL03_Authorization,                         RxBuffer_0x57D ,  	2 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  AL04_Authorization,                         RxBuffer_0x57D ,  	3 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  AL05_Authorization,                         RxBuffer_0x57D ,  	4 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  AL_BrightnessAdjust,                        RxBuffer_0x57D ,  	16	, 8   , 0 ,BYTE_ORDER_MOT},
	{  AL_ColorAdjust,                             RxBuffer_0x57D ,  	24	, 8   , 0 ,BYTE_ORDER_MOT},
	{  AL01_FadeEnable,                            RxBuffer_0x57D ,  	32	, 1   , 0 ,BYTE_ORDER_MOT},
	{  AL02_FadeEnable,                            RxBuffer_0x57D ,  	33	, 1   , 0 ,BYTE_ORDER_MOT},
	{  AL03_FadeEnable,                            RxBuffer_0x57D ,  	34	, 1   , 0 ,BYTE_ORDER_MOT},
	{  AL04_FadeEnable,                            RxBuffer_0x57D ,  	35	, 1   , 0 ,BYTE_ORDER_MOT},
	{  AL05_FadeEnable,                            RxBuffer_0x57D ,  	36	, 1   , 0 ,BYTE_ORDER_MOT},
	{  AL_FadeInSteptime,                          RxBuffer_0x57D ,  	48	, 8   , 0 ,BYTE_ORDER_MOT},
	{  AL_FadeOutSteptime,                         RxBuffer_0x57D ,  	56	, 8   , 0 ,BYTE_ORDER_MOT},
	{  MP5_DVR_Request,                            RxBuffer_0x5F7 ,  	0 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  MP5_HVAC_Auto_OnOff,                        RxBuffer_0x5F7 ,  	2 	, 2   , 0 ,BYTE_ORDER_MOT},
	{  MP5_AC_Dual_OnOff,                          RxBuffer_0x5F7 ,  	4 	, 2   , 0 ,BYTE_ORDER_MOT},
	{  MP5_AC_RightSetTemUpDown,                   RxBuffer_0x5F7 ,  	8 	, 2   , 0 ,BYTE_ORDER_MOT},
	{  MP5_AC_LeftSetTemUpDown,                    RxBuffer_0x5F7 ,  	10	, 2   , 0 ,BYTE_ORDER_MOT},
	{  MP5_AC_AllTemUpDown,                        RxBuffer_0x5F7 ,  	12	, 2   , 0 ,BYTE_ORDER_MOT},
	{  MP5_HVAC_On_Off,                            RxBuffer_0x5F7 ,  	14	, 2   , 0 ,BYTE_ORDER_MOT},
	{  MP5_AC_AllTem,                              RxBuffer_0x5F7 ,  	16	, 8   , 0 ,BYTE_ORDER_MOT},
	{  MP5RearDefrostOnOff,                        RxBuffer_0x5F7 ,  	24	, 2   , 0 ,BYTE_ORDER_MOT},
	{  Temp_level,                                 RxBuffer_0x5F7 ,  	28	, 4   , 0 ,BYTE_ORDER_MOT},
	{  MP5_Front_Defrost,                          RxBuffer_0x5F7 ,  	32	, 2   , 0 ,BYTE_ORDER_MOT},
	{  MP5_AC_BlowerLvUpDown,                      RxBuffer_0x5F7 ,  	34	, 2   , 0 ,BYTE_ORDER_MOT},
	{  MP5_AC_On_Off,                              RxBuffer_0x5F7 ,  	36	, 2   , 0 ,BYTE_ORDER_MOT},
	{  MP5_Air_In_Cycle,                           RxBuffer_0x5F7 ,  	38	, 2   , 0 ,BYTE_ORDER_MOT},
	{  MP5_AC_RightSetTem,                         RxBuffer_0x5F7 ,  	40	, 8   , 0 ,BYTE_ORDER_MOT},
	{  MP5_AC_LeftSetTem,                          RxBuffer_0x5F7 ,  	48	, 8   , 0 ,BYTE_ORDER_MOT},
	{  MP5_Mode_Change,                            RxBuffer_0x5F7 ,  	56	, 3   , 0 ,BYTE_ORDER_MOT},
	{  MP5_Fan_Speed,                              RxBuffer_0x5F7 ,  	60	, 4   , 0 ,BYTE_ORDER_MOT},
	{  TripmeterResetReq,                          RxBuffer_0x5F5 ,  	0 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  AvgFuelResetReq,                            RxBuffer_0x5F5 ,  	1 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  OdometerResetReq,                           RxBuffer_0x5F5 ,  	7 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  ChangeICMMode,                              RxBuffer_0x5F5 ,  	28	, 2   , 0 ,BYTE_ORDER_MOT},
	{  SpeedAlarmOnOff,                            RxBuffer_0x5F5 ,  	31	, 1   , 0 ,BYTE_ORDER_MOT},
	{  SpeedAlarmSet,                              RxBuffer_0x5F5 ,  	32	, 8   , 0 ,BYTE_ORDER_MOT},
	{  AlarmVolumeSet,                             RxBuffer_0x5F5 ,  	40	, 4   , 0 ,BYTE_ORDER_MOT},
	{  FuelConsumptionUnit,                        RxBuffer_0x5F5 ,  	44	, 1   , 0 ,BYTE_ORDER_MOT},
	{  LanguageSet,                                RxBuffer_0x5F5 ,  	45	, 3   , 0 ,BYTE_ORDER_MOT},
	{  OdometerDispSet,                            RxBuffer_0x5F5 ,  	48	, 1   , 0 ,BYTE_ORDER_MOT},
	{  MidSideDspType,                             RxBuffer_0x5F5 ,  	49	, 2   , 0 ,BYTE_ORDER_MOT},
	{  DispNavigatImage,                           RxBuffer_0x5F5 ,  	51	, 1   , 0 ,BYTE_ORDER_MOT},
	{  HU_ICM_Com_Sig,                             RxBuffer_0x632 ,  	56 	, 64  , 0 ,BYTE_ORDER_MOT},
	{  ECUSoftwareVersion,                         RxBuffer_0x576 ,  	32 	, 40  , 0 ,BYTE_ORDER_MOT},
	{  ECUHardwareVersion,                         RxBuffer_0x578 ,  	32 	, 40  , 0 ,BYTE_ORDER_MOT},
	{  AvgFuelConsumption,                         RxBuffer_0x519 ,  	0 	, 8   , 0 ,BYTE_ORDER_MOT},
	{  ResidueFuel,                                RxBuffer_0x519 ,  	8	, 8   , 0 ,BYTE_ORDER_MOT},
	{  DistanceEmpty,                              RxBuffer_0x519 ,  	28	, 12  , 0 ,BYTE_ORDER_MOT},
	{  ICM_mode_status,                            RxBuffer_0x519 ,  	24	, 2   , 0 ,BYTE_ORDER_MOT},
	{  ICM_MFSStatu,                               RxBuffer_0x519 ,  	27	, 1   , 0 ,BYTE_ORDER_MOT},
	{  Fuelsensorfailure,                          RxBuffer_0x519 ,  	34	, 1   , 0 ,BYTE_ORDER_MOT},
	{  ICM_OilPressureWarn,                        RxBuffer_0x519 ,  	35	, 1   , 0 ,BYTE_ORDER_MOT},
	{  EngCoolantTptWarn,                          RxBuffer_0x519 ,  	36	, 1   , 0 ,BYTE_ORDER_MOT},
	{  FuelWaringLevel,                            RxBuffer_0x519 ,  	37	, 1   , 0 ,BYTE_ORDER_MOT},
	{  BrakeFluidSW,                               RxBuffer_0x519 ,  	38	, 1   , 0 ,BYTE_ORDER_MOT},
	{  DispVehSpd,                                 RxBuffer_0x519 ,  	55	, 9   , 0 ,BYTE_ORDER_MOT},
	{  OccupantDetDRVSideVd,                       RxBuffer_0x519 ,  	48	, 1   , 0 ,BYTE_ORDER_MOT},
	{  OccupantDetDRVSide_0x519,                   RxBuffer_0x519 ,  	49	, 1   , 0 ,BYTE_ORDER_MOT},
	{  DISFail,                                    RxBuffer_0x519 ,  	51	, 1   , 0 ,BYTE_ORDER_MOT},
	{  QDashACCFail,                               RxBuffer_0x519 ,  	52	, 2   , 0 ,BYTE_ORDER_MOT},
	{  OdometerInfoVd,                             RxBuffer_0x3F7 ,  	0 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  OdometerInfo,                               RxBuffer_0x3F7 ,  	24	, 24  , 0 ,BYTE_ORDER_MOT},
	{  Rawvoltageratiooffuellevelinpercent,        RxBuffer_0x3F7 ,  	32	, 8   , 0 ,BYTE_ORDER_MOT},
	{  Unfilterfuellevel,                          RxBuffer_0x3F7 ,  	40	, 8   , 0 ,BYTE_ORDER_MOT},
	{  OiLResistance,                              RxBuffer_0x3F7 ,  	56	, 9   , 0 ,BYTE_ORDER_MOT},
	{  Fuellevelstate,                             RxBuffer_0x3F7 ,  	52	, 3   , 0 ,BYTE_ORDER_MOT},
	{  Fuellevelinvalid,                           RxBuffer_0x3F7 ,  	55	, 1   , 0 ,BYTE_ORDER_MOT},
	{  ICM_HU_Com_Sig,                             RxBuffer_0x631 ,  	56 	, 64  , 0 ,BYTE_ORDER_MOT},
	{  WLC_SW_Resp,                                RxBuffer_0x56F ,  	1 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  WLCState,                                   RxBuffer_0x56F ,  	2 	, 4   , 0 ,BYTE_ORDER_MOT},
	{  WLC_ModuleOff_0x56F,                        RxBuffer_0x56F ,  	7 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  DVR_TBOX_WiFiRequest,                       RxBuffer_0x5F6 ,  	0 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  DVR_TBOX_SocketRequest,                     RxBuffer_0x5F6 ,  	1 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  DoorCtrlReq,                                TxBuffer_0x5F0 ,  	0 	, 2   , 0 ,BYTE_ORDER_MOT},
	{  FindCarReq,                                 TxBuffer_0x5F0 ,  	2 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  OpenBackDoorReq,                            TxBuffer_0x5F0 ,  	5 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  TBOX_RemoteOpenPLG,                         TxBuffer_0x5F0 ,  	7 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  TBOX_RemoteStart,                           TxBuffer_0x5F0 ,  	8 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  TBOX_RemoteStop,                            TxBuffer_0x5F0 ,  	9 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  PoslampReq,                                 TxBuffer_0x5F0 ,  	10	, 2   , 0 ,BYTE_ORDER_MOT},
	{  TBOX_WL_Position_Req_FL,                    TxBuffer_0x5F0 ,  	12	, 4   , 0 ,BYTE_ORDER_MOT},
	{  TBOX_WL_Position_Req_FR,                    TxBuffer_0x5F0 ,  	16	, 4   , 0 ,BYTE_ORDER_MOT},
	{  SunRoofCtrlReq,                             TxBuffer_0x5F0 ,  	22	, 2   , 0 ,BYTE_ORDER_MOT},
	{  TBOX_WL_Position_Req_RR,                    TxBuffer_0x5F0 ,  	24	, 4   , 0 ,BYTE_ORDER_MOT},
	{  TBOX_BCM_RemoteAuthReq,                     TxBuffer_0x5F0 ,  	33	, 1   , 0 ,BYTE_ORDER_MOT},
	{  tbFLSeatHeatSET,                            TxBuffer_0x5F0 ,  	34	, 3   , 0 ,BYTE_ORDER_MOT},
	{  tbFRSeatHeatSET,                            TxBuffer_0x5F0 ,  	37	, 3   , 0 ,BYTE_ORDER_MOT},
	{  TBOX_WL_Position_Req_RL,                    TxBuffer_0x5F0 ,  	40	, 4   , 0 ,BYTE_ORDER_MOT},
	{  TBOX_RemoteFrontLftSeatHeat,                TxBuffer_0x5F0 ,  	44	, 3   , 0 ,BYTE_ORDER_MOT},
	{  TelemaStatus_L,                             TxBuffer_0x5F0 ,  	56	, 1   , 0 ,BYTE_ORDER_MOT},
	{  RemoteCutPwrReq,                            TxBuffer_0x5F0 ,  	57	, 1   , 0 ,BYTE_ORDER_MOT},
	{  RemoteExitPwrReq,                           TxBuffer_0x5F0 ,  	58	, 1   , 0 ,BYTE_ORDER_MOT},
	{  UpgradeSta,                                 TxBuffer_0x5F0 ,  	59	, 2   , 0 ,BYTE_ORDER_MOT},
	{  TBOX_DVR_VideoRequest,                      TxBuffer_0x5F0 ,  	61	, 1   , 0 ,BYTE_ORDER_MOT},
	{  TBOX_HVAC_ACMAX,                            TxBuffer_0x5F3 ,  	0 	, 2   , 0 ,BYTE_ORDER_MOT},
	{  TBOX_AirPurifMode,                          TxBuffer_0x5F3 ,  	8	, 3   , 0 ,BYTE_ORDER_MOT},
	{  TBOX_HVAC_AllTemUpDown,                     TxBuffer_0x5F3 ,  	11	, 2   , 0 ,BYTE_ORDER_MOT},
	{  TBOX_Mode_Change,                           TxBuffer_0x5F3 ,  	13	, 3   , 0 ,BYTE_ORDER_MOT},
	{  TBOX_HVAC_SetTem,                           TxBuffer_0x5F3 ,  	16	, 8   , 0 ,BYTE_ORDER_MOT},
	{  TBOX_HVAC_RearOnOff,                        TxBuffer_0x5F3 ,  	24	, 2   , 0 ,BYTE_ORDER_MOT},
	{  TBOX_HVAC_BlowerLvUpDown,                   TxBuffer_0x5F3 ,  	30	, 2   , 0 ,BYTE_ORDER_MOT},
	{  TBOX_AC_On_Off,                             TxBuffer_0x5F3 ,  	32	, 2   , 0 ,BYTE_ORDER_MOT},
	{  TBOX_Air_In_Cycle,                          TxBuffer_0x5F3 ,  	34	, 2   , 0 ,BYTE_ORDER_MOT},
	{  TBOX_Front_Defrost,                         TxBuffer_0x5F3 ,  	36	, 2   , 0 ,BYTE_ORDER_MOT},
	{  TBOX_HVAC_auto_on,                          TxBuffer_0x5F3 ,  	38	, 1   , 0 ,BYTE_ORDER_MOT},
	{  TBOX_AC_RightSetTem,                        TxBuffer_0x5F3 ,  	40	, 8   , 0 ,BYTE_ORDER_MOT},
	{  TBOX_AC_LeftSetTem, 					       TxBuffer_0x5F3 , 	48	, 8   , 0 ,BYTE_ORDER_MOT},
	{  TBOX_HVAC_Temp_level,                       TxBuffer_0x5F3 ,  	40	, 4   , 0 ,BYTE_ORDER_MOT},
	{  TBOX_HVAC_On_Off,                           TxBuffer_0x5F3 ,  	56	, 2   , 0 ,BYTE_ORDER_MOT},
	{  MP5_HVAC_Blower_Level,                      TxBuffer_0x5F3 ,  	58	, 4   , 0 ,BYTE_ORDER_MOT},
	{  TBOX__DVR_WiFi,                             TxBuffer_0x5F4 ,  	56 	, 64  , &dcs_TransmitSigFrameCfg_DIAG[DCS_TBOX_control1] ,BYTE_ORDER_MOT},
	{  TBOX__DVR_Socket,                           TxBuffer_0x5F8 ,  	56 	, 64  , &dcs_TransmitSigFrameCfg_DIAG[DCS_TBOX_control2] ,BYTE_ORDER_MOT},
	{  TBOX_NM_DestAdd,                            TxBuffer_0x40D ,  	0 	, 8   , 0 ,BYTE_ORDER_MOT},
	{  TBOX_NM_Alive,                              TxBuffer_0x40D ,  	8 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  TBOX_NM_Ring,                               TxBuffer_0x40D ,  	9 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  TBOX_NM_LimpHome,                           TxBuffer_0x40D ,  	10	, 1   , 0 ,BYTE_ORDER_MOT},
	{  TBOX_NM_SleepInd,                           TxBuffer_0x40D ,  	12	, 1   , 0 ,BYTE_ORDER_MOT},
	{  TBOX_NM_SleepAck,                           TxBuffer_0x40D ,  	13	, 1   , 0 ,BYTE_ORDER_MOT},
	{  TBOX_RemoteAuthResponse0,                   TxBuffer_0x533 ,  	0 	, 8   , &dcs_TransmitSigFrameCfg_DIAG[DCS_TBOX_RemoteAuthResponse_BCM] ,BYTE_ORDER_MOT},
	{  TBOX_RemoteAuthResponse1,                   TxBuffer_0x533 ,  	8	, 8   , &dcs_TransmitSigFrameCfg_DIAG[DCS_TBOX_RemoteAuthResponse_BCM] ,BYTE_ORDER_MOT},
	{  TBOX_RemoteAuthResponse2,                   TxBuffer_0x533 ,  	16	, 8   , &dcs_TransmitSigFrameCfg_DIAG[DCS_TBOX_RemoteAuthResponse_BCM] ,BYTE_ORDER_MOT},
	{  TBOX_RemoteAuthResponse3,                   TxBuffer_0x533 ,  	24	, 8   , &dcs_TransmitSigFrameCfg_DIAG[DCS_TBOX_RemoteAuthResponse_BCM] ,BYTE_ORDER_MOT},
	{  TBOX_RemoteAuthResponse4,                   TxBuffer_0x533 ,  	32	, 8   , &dcs_TransmitSigFrameCfg_DIAG[DCS_TBOX_RemoteAuthResponse_BCM] ,BYTE_ORDER_MOT},
	{  TBOX_RemoteAuthResponse5,                   TxBuffer_0x533 ,  	40	, 8   , &dcs_TransmitSigFrameCfg_DIAG[DCS_TBOX_RemoteAuthResponse_BCM] ,BYTE_ORDER_MOT},
	{  TBOX_RemoteAuthResponse6,                   TxBuffer_0x533 ,  	48	, 8   , &dcs_TransmitSigFrameCfg_DIAG[DCS_TBOX_RemoteAuthResponse_BCM] ,BYTE_ORDER_MOT},
	{  TBOX_RemoteAuthResponse7,                   TxBuffer_0x533 ,  	56	, 8   , &dcs_TransmitSigFrameCfg_DIAG[DCS_TBOX_RemoteAuthResponse_BCM] ,BYTE_ORDER_MOT},
	{  TBOXLearnSeed0,                             TxBuffer_0x536 ,  	0 	, 8   , &dcs_TransmitSigFrameCfg_DIAG[DCS_TBOX_LearnSeed_BCM] ,BYTE_ORDER_MOT},
	{  TBOXLearnSeed1,                             TxBuffer_0x536 ,  	8	, 8   , &dcs_TransmitSigFrameCfg_DIAG[DCS_TBOX_LearnSeed_BCM] ,BYTE_ORDER_MOT},
	{  TBOXLearnSeed2,                             TxBuffer_0x536 ,  	16	, 8   , &dcs_TransmitSigFrameCfg_DIAG[DCS_TBOX_LearnSeed_BCM] ,BYTE_ORDER_MOT},
	{  TBOXLearnSeed3,                             TxBuffer_0x536 ,  	24	, 8   , &dcs_TransmitSigFrameCfg_DIAG[DCS_TBOX_LearnSeed_BCM] ,BYTE_ORDER_MOT},
	{  TBOXLearnSeed4,                             TxBuffer_0x536 ,  	32	, 8   , &dcs_TransmitSigFrameCfg_DIAG[DCS_TBOX_LearnSeed_BCM] ,BYTE_ORDER_MOT},
	{  TBOXLearnSeed5,                             TxBuffer_0x536 ,  	40	, 8   , &dcs_TransmitSigFrameCfg_DIAG[DCS_TBOX_LearnSeed_BCM] ,BYTE_ORDER_MOT},
	{  TBOXLearnSeed6,                             TxBuffer_0x536 ,  	48	, 8   , &dcs_TransmitSigFrameCfg_DIAG[DCS_TBOX_LearnSeed_BCM] ,BYTE_ORDER_MOT},
	{  TBOXLearnSeed7,                             TxBuffer_0x536 ,  	56	, 8   , &dcs_TransmitSigFrameCfg_DIAG[DCS_TBOX_LearnSeed_BCM] ,BYTE_ORDER_MOT},
	{  TBOX_SN,                                    TxBuffer_0x5F9 ,  	56 	, 64  , &dcs_TransmitSigFrameCfg_DIAG[DCS_TBOX_control3] ,BYTE_ORDER_MOT},
	{  TBOX_VIN,                                   TxBuffer_0x5FA ,  	56 	, 64  , &dcs_TransmitSigFrameCfg_DIAG[DCS_TBOX_control4] ,BYTE_ORDER_MOT},
	{  IndicatorAutoFront,                         RxBuffer_0x3B3 ,  	1 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  IndicatorDefrostFront,                      RxBuffer_0x3B3 ,  	2 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  IndicatorACFront,                           RxBuffer_0x3B3 ,  	3 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  IndicatorOFFFront,                          RxBuffer_0x3B3 ,  	4 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  IndicatorIntCycleFront,                     RxBuffer_0x3B3 ,  	5 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  IndicatorDUALFront,                         RxBuffer_0x3B3 ,  	8 	, 2   , 0 ,BYTE_ORDER_MOT},
	{  HVAC_Diagnosis,                             RxBuffer_0x3B3 ,  	24	, 8   , 0 ,BYTE_ORDER_MOT},
	{  HURequest,                                  RxBuffer_0x3B3 ,  	59	, 1   , 0 ,BYTE_ORDER_MOT},
	{  HUCancel,                                   RxBuffer_0x3B3 ,  	60	, 1   , 0 ,BYTE_ORDER_MOT},
	{  ExtTempPect,                                RxBuffer_0x3B1 ,  	0 	, 8   , 0 ,BYTE_ORDER_MOT},
	{  eHVACTempLevel,                             RxBuffer_0x3B1 ,  	16	, 4   , 0 ,BYTE_ORDER_MOT},
	{  ModeDispFront,                              RxBuffer_0x3B1 ,  	24	, 4   , 0 ,BYTE_ORDER_MOT},
	{  HVAC_State,                                 RxBuffer_0x3B1 ,  	28	, 1   , 0 ,BYTE_ORDER_MOT},
	{  HVACDiagnosisReq,                           RxBuffer_0x3B1 ,  	29	, 1   , 0 ,BYTE_ORDER_MOT},
	{  ExtTempState,                               RxBuffer_0x3B1 ,  	30	, 2   , 0 ,BYTE_ORDER_MOT},
	{  FLSetTempDisp,                              RxBuffer_0x3B1 ,  	32	, 8   , 0 ,BYTE_ORDER_MOT},
	{  FRSetTempDisp,                              RxBuffer_0x3B1 ,  	40	, 8   , 0 ,BYTE_ORDER_MOT},
	{  ExtTempVd,                                  RxBuffer_0x3B1 ,  	48	, 1   , 0 ,BYTE_ORDER_MOT},
	{  ACReq,                                      RxBuffer_0x3B1 ,  	49	, 1   , 0 ,BYTE_ORDER_MOT},
	{  BlowerLvl,                                  RxBuffer_0x3B1 ,  	52	, 4   , 0 ,BYTE_ORDER_MOT},
	{  ExtTemp,                                    RxBuffer_0x3B1 ,  	56	, 8   , 0 ,BYTE_ORDER_MOT},
	{  KeyRearDefrost,                             RxBuffer_0x3BD ,  	1 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  KeyDefrostFront,                            RxBuffer_0x3BD ,  	6 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  KeyACFront,                                 RxBuffer_0x3BD ,  	8 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  KeyOFFFront,                                RxBuffer_0x3BD ,  	9 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  KeyAirCycleFront,                           RxBuffer_0x3BD ,  	10	, 1   , 0 ,BYTE_ORDER_MOT},
	{  KeyBlowerUpFront,                           RxBuffer_0x3BD ,  	11	, 1   , 0 ,BYTE_ORDER_MOT},
	{  KeyBlowerDownFront,                         RxBuffer_0x3BD ,  	12	, 1   , 0 ,BYTE_ORDER_MOT},
	{  KeyModeFront,                               RxBuffer_0x3BD ,  	13	, 1   , 0 ,BYTE_ORDER_MOT},
	{  keyESCFront,                                RxBuffer_0x3BD ,  	14	, 1   , 0 ,BYTE_ORDER_MOT},
	{  KeyHazardwaringLightFront,                  RxBuffer_0x3BD ,  	22	, 1   , 0 ,BYTE_ORDER_MOT},
	{  TCU_TsmSt1CheckSum,                         RxBuffer_0x266 ,  	0 	, 8   , 0 ,BYTE_ORDER_MOT},
	{  TCU_TsmSt1Counter,                          RxBuffer_0x266 ,  	8	, 4   , 0 ,BYTE_ORDER_MOT},
	{  CurrentGear,                                RxBuffer_0x266 ,  	12	, 4   , 0 ,BYTE_ORDER_MOT},
	{  CurrentGearVd,                              RxBuffer_0x266 ,  	16	, 1   , 0 ,BYTE_ORDER_MOT},
	{  TsmEmgOp,                                   RxBuffer_0x266 ,  	17	, 4   , 0 ,BYTE_ORDER_MOT},
	{  TsmAcousticWarning,                         RxBuffer_0x266 ,  	21	, 1   , 0 ,BYTE_ORDER_MOT},
	{  GearLvlUnlockWarning,                       RxBuffer_0x266 ,  	22	, 1   , 0 ,BYTE_ORDER_MOT},
	{  TsmFailure,                                 RxBuffer_0x266 ,  	30	, 1   , 0 ,BYTE_ORDER_MOT},
	{  TsmTempWarning,                             RxBuffer_0x266 ,  	32	, 2   , 0 ,BYTE_ORDER_MOT},
	{  TsmID,                                      RxBuffer_0x266 ,  	40	, 3   , 0 ,BYTE_ORDER_MOT},
	{  GearPsn,                                    RxBuffer_0x266 ,  	44	, 4   , 0 ,BYTE_ORDER_MOT},
	{  EgdGearDsp,                                 RxBuffer_0x266 ,  	48	, 4   , 0 ,BYTE_ORDER_MOT},
	{  DrvModDsp,                                  RxBuffer_0x266 ,  	52	, 4   , 0 ,BYTE_ORDER_MOT},
	{  TCUFeedback,                                RxBuffer_0x266 ,  	56	, 1   , 0 ,BYTE_ORDER_MOT},
	{  EmModeFlag,                                 RxBuffer_0x266 ,  	57	, 1   , 0 ,BYTE_ORDER_MOT},
	{  WarningLamp_CVT,                            RxBuffer_0x266 ,  	58	, 1   , 0 ,BYTE_ORDER_MOT},
	{  ESC_FrontWhlSpdCheckSum,                    RxBuffer_0x23C ,  	0 	, 8   , 0 ,BYTE_ORDER_MOT},
	{  VehSpdVd2,                                  RxBuffer_0x23C ,  	8 	, 2   , 0 ,BYTE_ORDER_MOT},
	{  ESC_FrontWhlSpdCounter,                     RxBuffer_0x23C ,  	12	, 4   , 0 ,BYTE_ORDER_MOT},
	{  VehSpd2,                                    RxBuffer_0x23C ,  	24	, 15  , 0 ,BYTE_ORDER_MOT},
	{  WhlSpdFR,                                   RxBuffer_0x23C ,  	40	, 13  , 0 ,BYTE_ORDER_MOT},
	{  WhlSpdFRVd,                                 RxBuffer_0x23C ,  	37	, 2   , 0 ,BYTE_ORDER_MOT},
	{  WhlSpdFL,                                   RxBuffer_0x23C ,  	56	, 13  , 0 ,BYTE_ORDER_MOT},
	{  WhlSpdFLVd,                                 RxBuffer_0x23C ,  	53	, 2   , 0 ,BYTE_ORDER_MOT},
	{  ESC_RearWhlSpdCheckSum,                     RxBuffer_0x23D ,  	0 	, 8   , 0 ,BYTE_ORDER_MOT},
	{  ESC_RearWhlSpdCounter,                      RxBuffer_0x23D ,  	12	, 4   , 0 ,BYTE_ORDER_MOT},
	{  WhlSpdRR,                                   RxBuffer_0x23D ,  	40	, 13  , 0 ,BYTE_ORDER_MOT},
	{  WhlSpdRRVd,                                 RxBuffer_0x23D ,  	37	, 2   , 0 ,BYTE_ORDER_MOT},
	{  WhlSpdRL,                                   RxBuffer_0x23D ,  	56	, 13  , 0 ,BYTE_ORDER_MOT},
	{  WhlSpdRLVd,                                 RxBuffer_0x23D ,  	53	, 2   , 0 ,BYTE_ORDER_MOT},
	{  LatAcc,                                     RxBuffer_0x21F ,  	62	, 10  , 0 ,BYTE_ORDER_MOT},
	{  ESC_WhlSpdDirCheckSum,                      RxBuffer_0x32A ,  	0 	, 8   , 0 ,BYTE_ORDER_MOT},
	{  FLWheelDir,                                 RxBuffer_0x32A ,  	8 	, 2   , 0 ,BYTE_ORDER_MOT},
	{  FRWheelDir,                                 RxBuffer_0x32A ,  	10	, 2   , 0 ,BYTE_ORDER_MOT},
	{  RLWheelDir,                                 RxBuffer_0x32A ,  	12	, 2   , 0 ,BYTE_ORDER_MOT},
	{  RRWheelDir,                                 RxBuffer_0x32A ,  	14	, 2   , 0 ,BYTE_ORDER_MOT},
	{  RRWheelSpdPulse,                            RxBuffer_0x32A ,  	25	, 11  , 0 ,BYTE_ORDER_MOT},
	{  ESC_WhlSpdDirCounter,                       RxBuffer_0x32A ,  	20	, 4   , 0 ,BYTE_ORDER_MOT},
	{  RLWheelSpdPulse,                            RxBuffer_0x32A ,  	30	, 11  , 0 ,BYTE_ORDER_MOT},
	{  FRWheelSpdPulse,                            RxBuffer_0x32A ,  	51	, 11  , 0 ,BYTE_ORDER_MOT},
	{  FLWheelSpdPulse,                            RxBuffer_0x32A ,  	56	, 11  , 0 ,BYTE_ORDER_MOT},
	{  PLG_SysStatus,                              RxBuffer_0x3CF ,  	0 	, 3   , 0 ,BYTE_ORDER_MOT},
	{  PLG_OpenPosition,                           RxBuffer_0x3CF ,  	8	, 3   , 0 ,BYTE_ORDER_MOT},
	{  PLG_FailStatus,                             RxBuffer_0x3CF ,  	32	, 1   , 0 ,BYTE_ORDER_MOT},
	{  PLG_Disable,                                RxBuffer_0x3CF ,  	33	, 1   , 0 ,BYTE_ORDER_MOT},
	{  PLG_FullOpenSetFlag,                        RxBuffer_0x3CF ,  	38	, 1   , 0 ,BYTE_ORDER_MOT},
	{  NeutralSw,                                  RxBuffer_0x11A ,  	0 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  ClutchTopSW,                                RxBuffer_0x11A ,  	1 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  ClutchBottomSW,                             RxBuffer_0x11A ,  	2 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  EMS_EngSt4MsgCounter,                       RxBuffer_0x11A ,  	4 	, 4   , 0 ,BYTE_ORDER_MOT},
	{  ClutchPsn,                                  RxBuffer_0x11A ,  	8	, 8   , 0 ,BYTE_ORDER_MOT},
	{  InsFuelConsumption,                         RxBuffer_0x11A ,  	16	, 8   , 0 ,BYTE_ORDER_MOT},
	{  EngspdIntvtime,                             RxBuffer_0x11A ,  	24	, 8   , 0 ,BYTE_ORDER_MOT},
	{  AtmPress,                                   RxBuffer_0x11A ,  	32	, 8   , 0 ,BYTE_ORDER_MOT},
	{  CruVehSpd,                                  RxBuffer_0x11A ,  	48	, 9   , 0 ,BYTE_ORDER_MOT},
	{  CruVehSpdVd,                                RxBuffer_0x11A ,  	41	, 1   , 0 ,BYTE_ORDER_MOT},
	{  EMS_EngSt4CheckSum,                         RxBuffer_0x11A ,  	56	, 8   , 0 ,BYTE_ORDER_MOT},
	{  VehSpd,                                     RxBuffer_0x20E ,  	8 	, 15  , 0 ,BYTE_ORDER_MOT},
	{  VehSpdVd,                                   RxBuffer_0x20E ,  	32	, 2   , 0 ,BYTE_ORDER_MOT},
	{  CrashInfo,                                  RxBuffer_0x20E ,  	37	, 1   , 0 ,BYTE_ORDER_MOT},
	{  EPBSts,                                     RxBuffer_0x20E ,  	58	, 3   , 0 ,BYTE_ORDER_MOT},
	{  AYCItvInProgress,                           RxBuffer_0x20E ,  	62	, 1   , 0 ,BYTE_ORDER_MOT},
	{  TCSItvInProgress,                           RxBuffer_0x20E ,  	63	, 1   , 0 ,BYTE_ORDER_MOT},
	{  IMMOFeedback,                               RxBuffer_0x247 ,  	1 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  AirbagFailSts,                              RxBuffer_0x247 ,  	3 	, 2   , 0 ,BYTE_ORDER_MOT},
	{  EPSFailure,                                 RxBuffer_0x247 ,  	5 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  EPSModeFeedback,                            RxBuffer_0x247 ,  	6 	, 2   , 0 ,BYTE_ORDER_MOT},
	{  OccupantDetDRVSide_0x247,                   RxBuffer_0x247 ,  	9 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  OccupantDetPsgSide,                         RxBuffer_0x247 ,  	10	, 1   , 0 ,BYTE_ORDER_MOT},
	{  OccupantDetRRSide,                          RxBuffer_0x247 ,  	11	, 1   , 0 ,BYTE_ORDER_MOT},
	{  OccupantDetRMSide,                          RxBuffer_0x247 ,  	12	, 1   , 0 ,BYTE_ORDER_MOT},
	{  OccupantDetRLSide,                          RxBuffer_0x247 ,  	13	, 1   , 0 ,BYTE_ORDER_MOT},
	{  GearUp,                                     RxBuffer_0x247 ,  	14	, 1   , 0 ,BYTE_ORDER_MOT},
	{  GearDown,                                   RxBuffer_0x247 ,  	15	, 1   , 0 ,BYTE_ORDER_MOT},
	{  DesireGear,                                 RxBuffer_0x247 ,  	16	, 4   , 0 ,BYTE_ORDER_MOT},
	{  ACM_ShiftTipInfo,                           RxBuffer_0x247 ,  	28	, 4   , 0 ,BYTE_ORDER_MOT},
	{  PFltRgn_StGPFLmp,                           RxBuffer_0x247 ,  	32	, 2   , 0 ,BYTE_ORDER_MOT},
	{  ACM_ErrorStatus,                            RxBuffer_0x247 ,  	39	, 1   , 0 ,BYTE_ORDER_MOT},
	{  HMA_Status_0x247,                           RxBuffer_0x247 ,  	40	, 3   , 0 ,BYTE_ORDER_MOT},
	{  HMA_HighbeamReq_0x247,                      RxBuffer_0x247 ,  	43	, 1   , 0 ,BYTE_ORDER_MOT},
	{  EPS_CalibrationSts,                         RxBuffer_0x247 ,  	51	, 1   , 0 ,BYTE_ORDER_MOT},
	{  DisplayInfo,                                RxBuffer_0x325 ,  	0 	, 4   , 0 ,BYTE_ORDER_MOT},
	{  FailureLampSts,                             RxBuffer_0x325 ,  	4 	, 2   , 0 ,BYTE_ORDER_MOT},
	{  FunctionLampSts,                            RxBuffer_0x325 ,  	6 	, 2   , 0 ,BYTE_ORDER_MOT},
	{  AutoHoldActive,                             RxBuffer_0x325 ,  	8 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  AutoHoldAvailable,                          RxBuffer_0x325 ,  	9 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  AutoholdFailure,                            RxBuffer_0x325 ,  	10	, 1   , 0 ,BYTE_ORDER_MOT},
	{  AutoHazardBlink,                            RxBuffer_0x325 ,  	11	, 2   , 0 ,BYTE_ORDER_MOT},
	{  ESCSw,                                      RxBuffer_0x325 ,  	13	, 1   , 0 ,BYTE_ORDER_MOT},
	{  ESCSwVd,                                    RxBuffer_0x325 ,  	14	, 1   , 0 ,BYTE_ORDER_MOT},
	{  HDCStatus,                                  RxBuffer_0x325 ,  	16	, 2   , 0 ,BYTE_ORDER_MOT},
	{  ECDActive,                                  RxBuffer_0x325 ,  	18	, 1   , 0 ,BYTE_ORDER_MOT},
	{  ECDAvailable,                               RxBuffer_0x325 ,  	19	, 1   , 0 ,BYTE_ORDER_MOT},
	{  HDCBrakeLightCtrl,                          RxBuffer_0x325 ,  	22	, 1   , 0 ,BYTE_ORDER_MOT},
	{  AutoHoldSWSts,                              RxBuffer_0x325 ,  	24	, 1   , 0 ,BYTE_ORDER_MOT},
	{  AutoHoldSWStsVd,                            RxBuffer_0x325 ,  	25	, 1   , 0 ,BYTE_ORDER_MOT},
	{  EPBSoundWarnSts,                            RxBuffer_0x325 ,  	26	, 2   , 0 ,BYTE_ORDER_MOT},
	{  AYCFailure,                                 RxBuffer_0x325 ,  	28	, 1   , 0 ,BYTE_ORDER_MOT},
	{  EBDFailure,                                 RxBuffer_0x325 ,  	29	, 1   , 0 ,BYTE_ORDER_MOT},
	{  ABSFailure,                                 RxBuffer_0x325 ,  	30	, 1   , 0 ,BYTE_ORDER_MOT},
	{  TCSFailure,                                 RxBuffer_0x325 ,  	31	, 1   , 0 ,BYTE_ORDER_MOT},
	{  AVHstandby,                                 RxBuffer_0x325 ,  	34	, 1   , 0 ,BYTE_ORDER_MOT},
	{  AEBdecActive,                               RxBuffer_0x325 ,  	35	, 1   , 0 ,BYTE_ORDER_MOT},
	{  AEBdecAvailable,                            RxBuffer_0x325 ,  	36	, 1   , 0 ,BYTE_ORDER_MOT},
	{  ESPAEBBAAct,                                RxBuffer_0x325 ,  	37	, 1   , 0 ,BYTE_ORDER_MOT},
	{  BrakelightReq,                              RxBuffer_0x325 ,  	38	, 2   , 0 ,BYTE_ORDER_MOT},
	{  APA_FuncSts,                                RxBuffer_0x249 ,  	8 	, 3   , 0 ,BYTE_ORDER_MOT},
	{  AEBDecCtrlRequest,                          RxBuffer_0x249 ,  	27	, 1   , 0 ,BYTE_ORDER_MOT},
	{  AWBRequest,                                 RxBuffer_0x249 ,  	28	, 1   , 0 ,BYTE_ORDER_MOT},
	{  EngInfo,                                    RxBuffer_0x117 ,  	0 	, 4   , 0 ,BYTE_ORDER_MOT},
	{  EMS_EngSt1MsgCounter,                       RxBuffer_0x117 ,  	4 	, 4   , 0 ,BYTE_ORDER_MOT},
	{  EngSpdVd,                                   RxBuffer_0x117 ,  	8 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  CruiseActive,                               RxBuffer_0x117 ,  	9 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  CruiseSwitch,                               RxBuffer_0x117 ,  	10	, 1   , 0 ,BYTE_ORDER_MOT},
	{  EngState,                                   RxBuffer_0x117 ,  	11	, 2   , 0 ,BYTE_ORDER_MOT},
	{  EngSpd,                                     RxBuffer_0x117 ,  	24	, 16  , 0 ,BYTE_ORDER_MOT},
	{  BrkPdlPsnNO,                                RxBuffer_0x117 ,  	33	, 1   , 0 ,BYTE_ORDER_MOT},
	{  EngMIL,                                     RxBuffer_0x117 ,  	34	, 1   , 0 ,BYTE_ORDER_MOT},
	{  EngIdleStatus,                              RxBuffer_0x117 ,  	35	, 1   , 0 ,BYTE_ORDER_MOT},
	{  EngFailure,                                 RxBuffer_0x117 ,  	37	, 1   , 0 ,BYTE_ORDER_MOT},
	{  GasPdlPsnVd,                                RxBuffer_0x117 ,  	38	, 1   , 0 ,BYTE_ORDER_MOT},
	{  EMS_EngSt1CheckSum,                         RxBuffer_0x117 ,  	40	, 8   , 0 ,BYTE_ORDER_MOT},
	{  GasPdlPsn,                                  RxBuffer_0x117 ,  	48	, 8   , 0 ,BYTE_ORDER_MOT},
	{  EngCoolantTpt,                              RxBuffer_0x117 ,  	56  , 8   , 0 ,BYTE_ORDER_MOT},
	{  ACCSetCruVehSpdDis,                         RxBuffer_0x390 ,     15 	, 9   , 0 ,BYTE_ORDER_MOT},
	{  DxTarObj,                                   RxBuffer_0x390 ,  	8 	, 2   , 0 ,BYTE_ORDER_MOT},
	{  TauGapSet,                                  RxBuffer_0x390 ,  	10	, 2   , 0 ,BYTE_ORDER_MOT},
	{  ObjValid,                                   RxBuffer_0x390 ,  	12	, 1   , 0 ,BYTE_ORDER_MOT},
	{  TakeOverReq,                                RxBuffer_0x390 ,  	13	, 1   , 0 ,BYTE_ORDER_MOT},
	{  Textinfo,                                   RxBuffer_0x390 ,  	16	, 4   , 0 ,BYTE_ORDER_MOT},
	{  ACC_SysStHMI_AliveCounter,                  RxBuffer_0x390 ,  	20	, 4   , 0 ,BYTE_ORDER_MOT},
	{  ACCMode_HMI,                                RxBuffer_0x390 ,  	24	, 3   , 0 ,BYTE_ORDER_MOT},
	{  PCW_latentWarning,                          RxBuffer_0x390 ,  	27	, 1   , 0 ,BYTE_ORDER_MOT},
	{  PCW_preWarning,                             RxBuffer_0x390 ,  	28	, 1   , 0 ,BYTE_ORDER_MOT},
	{  FRS_FCW_Switch,                             RxBuffer_0x390 ,  	29	, 1   , 0 ,BYTE_ORDER_MOT},
	{  FRS_AEB_Switch,                             RxBuffer_0x390 ,  	30	, 1   , 0 ,BYTE_ORDER_MOT},
	{  FRS_AEB_Status,                             RxBuffer_0x390 ,  	31	, 1   , 0 ,BYTE_ORDER_MOT},
	{  FRS_FCW_status,                             RxBuffer_0x390 ,  	32	, 1   , 0 ,BYTE_ORDER_MOT},
	{  FRS_AEB_status_testinfo,                    RxBuffer_0x390 ,  	33	, 2   , 0 ,BYTE_ORDER_MOT},
	{  MRR_FCWSensitivity,                         RxBuffer_0x390 ,  	35	, 2   , 0 ,BYTE_ORDER_MOT},
	{  SAS_CalibrationSts,                         RxBuffer_0x135 ,  	13	, 1   , 0 ,BYTE_ORDER_MOT},
	{  SAS_SteerWheelAngle,                        RxBuffer_0x135 ,  	24	, 16  , 0 ,BYTE_ORDER_MOT},
	{  SAS_SteerWheelRotSpd,                       RxBuffer_0x135 ,  	32	, 8   , 0 ,BYTE_ORDER_MOT},
	{  FFLPDCDistance,                             RxBuffer_0x525 ,  	0 	, 5   , 0 ,BYTE_ORDER_MOT},
	{  FSLPDCDistance,                             RxBuffer_0x525 ,  	8	, 5   , 0 ,BYTE_ORDER_MOT},
	{  FSRPDCDistance,                             RxBuffer_0x525 ,  	16	, 5   , 0 ,BYTE_ORDER_MOT},
	{  FFRPDCDistance,                             RxBuffer_0x525 ,  	24	, 5   , 0 ,BYTE_ORDER_MOT},
	{  RFLPDCDistance,                             RxBuffer_0x525 ,  	32	, 5   , 0 ,BYTE_ORDER_MOT},
	{  PDCDetectingSts,                            RxBuffer_0x525 ,  	37	, 3   , 0 ,BYTE_ORDER_MOT},
	{  RSLPDCDistance,                             RxBuffer_0x525 ,  	40	, 5   , 0 ,BYTE_ORDER_MOT},
	{  RPDCAudioResp,                              RxBuffer_0x525 ,  	45	, 3   , 0 ,BYTE_ORDER_MOT},
	{  RSRPDCDistance,                             RxBuffer_0x525 ,  	48	, 5   , 0 ,BYTE_ORDER_MOT},
	{  PDCwarning,                                 RxBuffer_0x525 ,  	53	, 3   , 0 ,BYTE_ORDER_MOT},
	{  RFRPDCDistance,                             RxBuffer_0x525 ,  	56	, 5   , 0 ,BYTE_ORDER_MOT},
	{  PAS_SW,                                     RxBuffer_0x525 ,  	61	, 1   , 0 ,BYTE_ORDER_MOT},
	{  PDCSysSts,                                  RxBuffer_0x525 ,  	62	, 2   , 0 ,BYTE_ORDER_MOT},
	{  HMA_Status_0x260,                           RxBuffer_0x260 ,  	0 	, 3   , 0 ,BYTE_ORDER_MOT},
	{  HMA_HighbeamReq_0x260,                      RxBuffer_0x260 ,  	3 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  ADAS_LeftTrackingStatus,                    RxBuffer_0x260 ,  	4 	, 2   , 0 ,BYTE_ORDER_MOT},
	{  ADAS_RightTrackingStatus,                   RxBuffer_0x260 ,  	6	, 2   , 0 ,BYTE_ORDER_MOT},
	{  LDW_Status,                                 RxBuffer_0x260 ,  	8	, 3   , 0 ,BYTE_ORDER_MOT},
	{  ADAS_Sensitivity,                           RxBuffer_0x260 ,  	11	, 2   , 0 ,BYTE_ORDER_MOT},
	{  ADAS_LaneAssitType,                         RxBuffer_0x260 ,  	13	, 2   , 0 ,BYTE_ORDER_MOT},
	{  ADAS_TakeoverReq,                           RxBuffer_0x260 ,  	15	, 1   , 0 ,BYTE_ORDER_MOT},
	{  ADAS_Status,                                RxBuffer_0x260 ,  	16	, 3   , 0 ,BYTE_ORDER_MOT},
	{  ADAS_WarningAudio,                          RxBuffer_0x260 ,  	20	, 1   , 0 ,BYTE_ORDER_MOT},
	{  SLAState,                                   RxBuffer_0x260 ,  	21	, 3   , 0 ,BYTE_ORDER_MOT},
	{  MPC_AliveCounter,                           RxBuffer_0x260 ,  	24	, 4   , 0 ,BYTE_ORDER_MOT},
	{  ADAS_TorqueReqStatus,                       RxBuffer_0x260 ,  	28	, 2   , 0 ,BYTE_ORDER_MOT},
	{  FCW_Warning,                                RxBuffer_0x260 ,  	30	, 2   , 0 ,BYTE_ORDER_MOT},
	{  SLASpdlimit,                                RxBuffer_0x260 ,  	43	, 6   , 0 ,BYTE_ORDER_MOT},
	{  FCWResp,                                    RxBuffer_0x260 ,  	33	, 1   , 0 ,BYTE_ORDER_MOT},
	{  FCWSensiResp,                               RxBuffer_0x260 ,  	34	, 2   , 0 ,BYTE_ORDER_MOT},
	{  FCW_State,                                  RxBuffer_0x260 ,  	36	, 3   , 0 ,BYTE_ORDER_MOT},
	{  FCW_Error_Status,                           RxBuffer_0x260 ,  	39	, 1   , 0 ,BYTE_ORDER_MOT},
	{  ADAS_TorqueReq,                             RxBuffer_0x260 ,  	48	, 11  , 0 ,BYTE_ORDER_MOT},
	{  MPC_CheckSum,                               RxBuffer_0x260 ,  	56	, 8   , 0 ,BYTE_ORDER_MOT},
	{  APA_PDCRearMidLeftRegObjSts,                RxBuffer_0x39A ,  	0 	, 5   , 0 ,BYTE_ORDER_MOT},//0222修改信号名与DBC保持一致
	{  APA_PDCSysSts,                              RxBuffer_0x39A ,  	5	, 2   , 0 ,BYTE_ORDER_MOT},
	{  APA_PDCFailureWarning,                      RxBuffer_0x39A ,  	7	, 1   , 0 ,BYTE_ORDER_MOT},
	{  APA_PDCRearLeftRegObjSts,                   RxBuffer_0x39A ,  	8	, 5   , 0 ,BYTE_ORDER_MOT},
	{  APA_PDCAudibleFrontBeepRate,                RxBuffer_0x39A ,  	13	, 3   , 0 ,BYTE_ORDER_MOT},
	{  APA_PDCFrontLeftRegObjSts,                  RxBuffer_0x39A ,  	16	, 5   , 0 ,BYTE_ORDER_MOT},
	{  APA_PDCAudibleRearBeepRate,                 RxBuffer_0x39A ,  	21	, 3   , 0 ,BYTE_ORDER_MOT},
	{  APA_PDCRearRightRegObjSts,                  RxBuffer_0x39A ,  	27	, 5   , 0 ,BYTE_ORDER_MOT},
	{  APA_PDCFrontMidLeftRegObjSts,               RxBuffer_0x39A ,  	32	, 5   , 0 ,BYTE_ORDER_MOT},
	{  APA_PDCFrontRightRegObjSts,                 RxBuffer_0x39A ,  	38	, 5   , 0 ,BYTE_ORDER_MOT},
	{  APA_PDCRearMidRightRegObjSts,               RxBuffer_0x39A ,  	43	, 5   , 0 ,BYTE_ORDER_MOT},
	{  apa_avmSts,                            	   RxBuffer_0x39A ,  	48	, 4   , 0 ,BYTE_ORDER_MOT},
	{  apa_WarningReq,                             RxBuffer_0x39A ,  	52	, 1   , 0 ,BYTE_ORDER_MOT},
	{  APA_PDCFrontMidRightRegObjSts,              RxBuffer_0x39A ,  	54	, 5   , 0 ,BYTE_ORDER_MOT},
	{  Win_Position_RSD_FL,                        RxBuffer_0x361 ,  	0 	, 8   , 0 ,BYTE_ORDER_MOT},
	{  Win_Position_RSD_FR,                        RxBuffer_0x361 ,  	8	, 8   , 0 ,BYTE_ORDER_MOT},
	{  Win_Position_RSD_RL,                        RxBuffer_0x361 ,  	16	, 8   , 0 ,BYTE_ORDER_MOT},
	{  Win_Position_RSD_RR,                        RxBuffer_0x361 ,  	24	, 8   , 0 ,BYTE_ORDER_MOT},
	{  FLSeatHeatIndicator,                        RxBuffer_0x361 ,  	32	, 3   , 0 ,BYTE_ORDER_MOT},
	{  FRSeatHeatIndicator,                        RxBuffer_0x361 ,  	35	, 3   , 0 ,BYTE_ORDER_MOT},
	{  RMAvailableResp,                            RxBuffer_0x361 ,  	38	, 1   , 0 ,BYTE_ORDER_MOT},
	{  RMBackDownResp,                             RxBuffer_0x361 ,  	39	, 1   , 0 ,BYTE_ORDER_MOT},
	{  PowerWindowPinchProtectionAlarm,            RxBuffer_0x361 ,  	40	, 1   , 0 ,BYTE_ORDER_MOT},
	{  WinSuppressionSt,                           RxBuffer_0x361 ,  	41	, 1   , 0 ,BYTE_ORDER_MOT},
	{  RemoteOpenWindow,                           RxBuffer_0x361 ,  	44	, 2   , 0 ,BYTE_ORDER_MOT},
	{  RemoteCloseWindow,                          RxBuffer_0x361 ,  	46	, 2   , 0 ,BYTE_ORDER_MOT},
	{  ConditionNotCorrect_0x361,                  RxBuffer_0x361 ,  	48	, 3   , 0 ,BYTE_ORDER_MOT},
	{  MemorySoundSts,                             RxBuffer_0x361 ,  	51	, 1   , 0 ,BYTE_ORDER_MOT},
	{  SeatGreeterStatus,                          RxBuffer_0x361 ,  	52	, 1   , 0 ,BYTE_ORDER_MOT},
	{  FLSeatVentIndicator,                        RxBuffer_0x361 ,  	56	, 3   , 0 ,BYTE_ORDER_MOT},
	{  FRSeatVentIndicator,                        RxBuffer_0x361 ,  	59	, 3   , 0 ,BYTE_ORDER_MOT},
	{  BSD_FUNCTION_Resp,                          RxBuffer_0x50A ,  	0 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  BSD_LCMA_SW_Resp,                           RxBuffer_0x50A ,  	1 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  CTA_SW_Resp,                                RxBuffer_0x50A ,  	2 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  RCW_SW_Resp,                                RxBuffer_0x50A ,  	3 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  PW_SW_Resp,                                 RxBuffer_0x50A ,  	4 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  PW_STATUS_L,                                RxBuffer_0x50A ,  	5 	, 2   , 0 ,BYTE_ORDER_MOT},
	{  BSD_LCMA_STATUS_L,                          RxBuffer_0x50A ,  	8 	, 2   , 0 ,BYTE_ORDER_MOT},
	{  CTA_STATUS_L,                               RxBuffer_0x50A ,  	10	, 2   , 0 ,BYTE_ORDER_MOT},
	{  RCW_STATUS_L,                               RxBuffer_0x50A ,  	12	, 2   , 0 ,BYTE_ORDER_MOT},
	{  PW_STATUS_R,                                RxBuffer_0x50A ,  	14	, 2   , 0 ,BYTE_ORDER_MOT},
	{  BSD_LCMA_STATUS_R,                          RxBuffer_0x50A ,  	16	, 2   , 0 ,BYTE_ORDER_MOT},
	{  CTA_STATUS_R,                               RxBuffer_0x50A ,  	18	, 2   , 0 ,BYTE_ORDER_MOT},
	{  RCW_STATUS_R,                               RxBuffer_0x50A ,  	20	, 2   , 0 ,BYTE_ORDER_MOT},
	{  SYSTEM_STATUS,                              RxBuffer_0x50A ,  	24	, 3   , 0 ,BYTE_ORDER_MOT},
	{  FLTirePres,                                 RxBuffer_0x317 ,  	0 	, 8   , 0 ,BYTE_ORDER_MOT},
	{  FRTirePres,                                 RxBuffer_0x317 ,  	8	, 8   , 0 ,BYTE_ORDER_MOT},
	{  RLTirePres,                                 RxBuffer_0x317 ,  	16	, 8   , 0 ,BYTE_ORDER_MOT},
	{  RRTirePres,                                 RxBuffer_0x317 ,  	24	, 8   , 0 ,BYTE_ORDER_MOT},
	{  FLPressureWarning,                          RxBuffer_0x317 ,  	32	, 3   , 0 ,BYTE_ORDER_MOT},
	{  FRPressureWarning,                          RxBuffer_0x317 ,  	35	, 3   , 0 ,BYTE_ORDER_MOT},
	{  RLPressureWarning,                          RxBuffer_0x317 ,  	40	, 3   , 0 ,BYTE_ORDER_MOT},
	{  RRPressureWarning,                          RxBuffer_0x317 ,  	43	, 3   , 0 ,BYTE_ORDER_MOT},
	{  FLTempHigh,                                 RxBuffer_0x317 ,  	46	, 1   , 0 ,BYTE_ORDER_MOT},
	{  FRTempHigh,                                 RxBuffer_0x317 ,  	47	, 1   , 0 ,BYTE_ORDER_MOT},
	{  RLTempHigh,                                 RxBuffer_0x317 ,  	48	, 1   , 0 ,BYTE_ORDER_MOT},
	{  RRTempHigh,                                 RxBuffer_0x317 ,  	49	, 1   , 0 ,BYTE_ORDER_MOT},
	{  SystemWarning,                              RxBuffer_0x317 ,  	51	, 1   , 0 ,BYTE_ORDER_MOT},
	{  StudyFailureWarning,                        RxBuffer_0x317 ,  	52	, 1   , 0 ,BYTE_ORDER_MOT},
	{  FLTireTemp,                                 RxBuffer_0x3A2 ,  	0 	, 8   , 0 ,BYTE_ORDER_MOT},
	{  FRTireTemp,                                 RxBuffer_0x3A2 ,  	8	, 8   , 0 ,BYTE_ORDER_MOT},
	{  RLTireTemp,                                 RxBuffer_0x3A2 ,  	16	, 8   , 0 ,BYTE_ORDER_MOT},
	{  RRTireTemp,                                 RxBuffer_0x3A2 ,  	24	, 8   , 0 ,BYTE_ORDER_MOT},
	{  SecurityStatus,                             RxBuffer_0x2AB ,  	0 	, 3   , 0 ,BYTE_ORDER_MOT},
	{  DrvLockCommand,                             RxBuffer_0x2AB ,  	3 	, 4   , 0 ,BYTE_ORDER_MOT},
	{  PLGDeCL_KeyWithinScope,                     RxBuffer_0x2AB ,  	8 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  DRLLamp,                                    RxBuffer_0x2AB ,  	9 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  DayNightStatus,                             RxBuffer_0x2AB ,  	10	, 1   , 0 ,BYTE_ORDER_MOT},
	{  BCM_RemoteKeyID,                            RxBuffer_0x2AB ,  	11	, 3   , 0 ,BYTE_ORDER_MOT},
	{  BackLightControl,                           RxBuffer_0x2AB ,  	14	, 2   , 0 ,BYTE_ORDER_MOT},
	{  LockCtrl,                                   RxBuffer_0x2AB ,  	16	, 8   , 0 ,BYTE_ORDER_MOT},
	{  BCM_BackLightLvl,                           RxBuffer_0x2AB ,  	24	, 8   , 0 ,BYTE_ORDER_MOT},
	{  DirIndicationLeft,                          RxBuffer_0x2AB ,  	32	, 1   , 0 ,BYTE_ORDER_MOT},
	{  DirIndicationRight,                         RxBuffer_0x2AB ,  	33	, 1   , 0 ,BYTE_ORDER_MOT},
	{  TurnSwitch,                                 RxBuffer_0x2AB ,  	34	, 2   , 0 ,BYTE_ORDER_MOT},
	{  HandBrakingStatus,                          RxBuffer_0x2AB ,  	36	, 1   , 0 ,BYTE_ORDER_MOT},
	{  RainCloseWndReq,                            RxBuffer_0x2AB ,  	38	, 1   , 0 ,BYTE_ORDER_MOT},
	{  QuitMoniCloseWndReq,                        RxBuffer_0x2AB ,  	39	, 1   , 0 ,BYTE_ORDER_MOT},
	{  KeyState,                                   RxBuffer_0x2AB ,  	40	, 3   , 0 ,BYTE_ORDER_MOT},
	{  BCM_KeyState_VD,                            RxBuffer_0x2AB ,  	43	, 2   , 0 ,BYTE_ORDER_MOT},
	{  TurnSwitchVd,                               RxBuffer_0x2AB ,  	45	, 1   , 0 ,BYTE_ORDER_MOT},
	{  FrontWiperStatus,                           RxBuffer_0x2AB ,  	46	, 2   , 0 ,BYTE_ORDER_MOT},
	{  AlarmLevelStatus,                           RxBuffer_0x2AB ,  	48	, 3   , 0 ,BYTE_ORDER_MOT},
	{  HazardWarningLightSW,                       RxBuffer_0x2CD ,  	0 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  RearWiperCtrl,                              RxBuffer_0x2CD ,  	1 	, 2   , 0 ,BYTE_ORDER_MOT},
	{  FrontWindscreenWashSW,                      RxBuffer_0x2CD ,  	3 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  FrontWiperIntAutoSW,                        RxBuffer_0x2CD ,  	4 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  KeyInHoleStatus,                            RxBuffer_0x2CD ,  	5 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  AutoLightSW,                                RxBuffer_0x2CD ,  	6 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  SolarSensorFaultPresent,                    RxBuffer_0x2CD ,  	7 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  BCM_searchstate,                            RxBuffer_0x2CD ,  	8 	, 2   , 0 ,BYTE_ORDER_MOT},
	{  BCM_RemoteAuthstate,                        RxBuffer_0x2CD ,  	11	, 2   , 0 ,BYTE_ORDER_MOT},
	{  BCM_RemoteFeedback,                         RxBuffer_0x2CD ,  	13	, 3   , 0 ,BYTE_ORDER_MOT},
	{  LeftSolarSensorValue,                       RxBuffer_0x2CD ,  	16	, 8   , 0 ,BYTE_ORDER_MOT},
	{  RightSolarSensorValue,                      RxBuffer_0x2CD ,  	24	, 8   , 0 ,BYTE_ORDER_MOT},
	{  LeftChildUnlockState,                       RxBuffer_0x2CD ,  	32	, 1   , 0 ,BYTE_ORDER_MOT},
	{  RightChildUnlockState,                      RxBuffer_0x2CD ,  	33	, 1   , 0 ,BYTE_ORDER_MOT},
	{  KickSNRReq,                                 RxBuffer_0x2CD ,  	34	, 1   , 0 ,BYTE_ORDER_MOT},
	{  ReverseSW,                                  RxBuffer_0x2CD ,  	35	, 1   , 0 ,BYTE_ORDER_MOT},
	{  SSD_PosStatus,                              RxBuffer_0x2CD ,  	36	, 4   , 0 ,BYTE_ORDER_MOT},
	{  SRF_PosStatus,                              RxBuffer_0x2CD ,  	40	, 4   , 0 ,BYTE_ORDER_MOT},
	{  WiperMaintainSts,                           RxBuffer_0x2CD ,  	44	, 1   , 0 ,BYTE_ORDER_MOT},
	{  BCM_FrontWiperSW,                           RxBuffer_0x2CD ,  	45	, 3   , 0 ,BYTE_ORDER_MOT},
	{  Poslamp,                                    RxBuffer_0x2CD ,  	48	, 1   , 0 ,BYTE_ORDER_MOT},
	{  Trunk_BackDoor_Sts,                         RxBuffer_0x2CD ,  	49	, 1   , 0 ,BYTE_ORDER_MOT},
	{  LedLeftStatus,                              RxBuffer_0x2CD ,  	50	, 1   , 0 ,BYTE_ORDER_MOT},
	{  HoodStatus,                                 RxBuffer_0x2CD ,  	51	, 1   , 0 ,BYTE_ORDER_MOT},
	{  HeadLampHighBeamCtrl,                       RxBuffer_0x2CD ,  	52	, 1   , 0 ,BYTE_ORDER_MOT},
	{  FrontFogLamp,                               RxBuffer_0x2CD ,  	53	, 1   , 0 ,BYTE_ORDER_MOT},
	{  DRVUnlockState,                             RxBuffer_0x2CD ,  	54	, 1   , 0 ,BYTE_ORDER_MOT},
	{  HeadLampLowBeamCtrl,                        RxBuffer_0x2CD ,  	55	, 1   , 0 ,BYTE_ORDER_MOT},
	{  DrvDoorStatus,                              RxBuffer_0x2CD ,  	56	, 1   , 0 ,BYTE_ORDER_MOT},
	{  PsgDoorStatus,                              RxBuffer_0x2CD ,  	57	, 1   , 0 ,BYTE_ORDER_MOT},
	{  RRDoorStatus,                               RxBuffer_0x2CD ,  	58	, 1   , 0 ,BYTE_ORDER_MOT},
	{  RLDoorStatus,                               RxBuffer_0x2CD ,  	59	, 1   , 0 ,BYTE_ORDER_MOT},
	{  DefrostCtrl,                                RxBuffer_0x2CD ,  	60	, 1   , 0 ,BYTE_ORDER_MOT},
	{  RearFogLamp,                                RxBuffer_0x2CD ,  	61	, 1   , 0 ,BYTE_ORDER_MOT},
	{  LedRightStatus,                             RxBuffer_0x2CD ,  	63	, 1   , 0 ,BYTE_ORDER_MOT},
	{  LightDelayOutResp,                          RxBuffer_0x29A ,  	0 	, 3   , 0 ,BYTE_ORDER_MOT},
	{  LightDelayInResp,                           RxBuffer_0x29A ,  	3 	, 3   , 0 ,BYTE_ORDER_MOT},
	{  LightPostonAvailableResp,                   RxBuffer_0x29A ,  	7 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  BCM_CustomizationList,                      RxBuffer_0x29A ,  	24	, 16  , 0 ,BYTE_ORDER_MOT},
	{  HornAlertVolumeResp,                        RxBuffer_0x29A ,  	33	, 2   , 0 ,BYTE_ORDER_MOT},
	{  BCM_MechanicalKeyGuardState,                RxBuffer_0x29A ,  	35	, 1   , 0 ,BYTE_ORDER_MOT},
	{  BCM_SpeedLockValue,                         RxBuffer_0x29A ,  	36	, 2   , 0 ,BYTE_ORDER_MOT},
	{  BCM_WindowRemoteAutoDownState,              RxBuffer_0x29A ,  	38	, 1   , 0 ,BYTE_ORDER_MOT},
	{  BCM_AutoWiperState,                         RxBuffer_0x29A ,  	39	, 1   , 0 ,BYTE_ORDER_MOT},
	{  BCM_AssistIlluminationState,                RxBuffer_0x29A ,  	40	, 1   , 0 ,BYTE_ORDER_MOT},
	{  BCM_BacklightLevelState,                    RxBuffer_0x29A ,  	41	, 2   , 0 ,BYTE_ORDER_MOT},
	{  BCM_exRearMirrorAutoFold,                   RxBuffer_0x29A ,  	47	, 1   , 0 ,BYTE_ORDER_MOT},
	{  BCMDiagnosticFlag,                          RxBuffer_0x29A ,  	48	, 2   , 0 ,BYTE_ORDER_MOT},
	{  DiagHeadLampLowBeam,                        RxBuffer_0x29A ,  	50	, 1   , 0 ,BYTE_ORDER_MOT},
	{  DiagHeadLampHighBeam,                       RxBuffer_0x29A ,  	51	, 1   , 0 ,BYTE_ORDER_MOT},
	{  DiagPosLam,                                 RxBuffer_0x29A ,  	52	, 2   , 0 ,BYTE_ORDER_MOT},
	{  DiagLeftTurnLight,                          RxBuffer_0x29A ,  	54	, 2   , 0 ,BYTE_ORDER_MOT},
	{  DiagRightTurnLight,                         RxBuffer_0x29A ,  	56	, 2   , 0 ,BYTE_ORDER_MOT},
	{  DiagStopLamp,                               RxBuffer_0x29A ,  	58	, 2   , 0 ,BYTE_ORDER_MOT},
	{  DiagHighMountStopLamp,                      RxBuffer_0x29A ,  	60	, 2   , 0 ,BYTE_ORDER_MOT},
	{  DiagRearFogLamp,                            RxBuffer_0x29A ,  	62	, 2   , 0 ,BYTE_ORDER_MOT},
	{  RemoteStartFailCause,                       RxBuffer_0x340 ,  	22	, 3   , 0 ,BYTE_ORDER_MOT},
	{  RemotePLGUnlock,                            RxBuffer_0x340 ,  	36	, 2   , 0 ,BYTE_ORDER_MOT},
	{  RemoteIGNOnFailCause,                       RxBuffer_0x340 ,  	41	, 3   , 0 ,BYTE_ORDER_MOT},
	{  RemoteSearch,                               RxBuffer_0x340 ,  	44	, 2   , 0 ,BYTE_ORDER_MOT},
	{  RemoteLock,                                 RxBuffer_0x340 ,  	46	, 2   , 0 ,BYTE_ORDER_MOT},
	{  RemoteUnlock,                               RxBuffer_0x340 ,  	48	, 2   , 0 ,BYTE_ORDER_MOT},
	{  RemoteTrunkUnlock,                          RxBuffer_0x340 ,  	52	, 2   , 0 ,BYTE_ORDER_MOT},
	{  BCMComStatus,                               RxBuffer_0x340 ,  	54	, 1   , 0 ,BYTE_ORDER_MOT},
	{  SecondLock,                                 RxBuffer_0x340 ,  	55	, 1   , 0 ,BYTE_ORDER_MOT},
	{  ConditionNotCorrect_0x340,                  RxBuffer_0x340 ,  	56	, 4   , 0 ,BYTE_ORDER_MOT},
	{  RemoteCloseSunRoof,                         RxBuffer_0x340 ,  	60	, 2   , 0 ,BYTE_ORDER_MOT},
	{  RemoteopenSunRoof,                          RxBuffer_0x340 ,  	62	, 2   , 0 ,BYTE_ORDER_MOT},
	{  OrderInformation,                           RxBuffer_0x2C1 ,  	0 	, 4   , 0 ,BYTE_ORDER_MOT},
	{  ExtKeyID,                                   RxBuffer_0x2C1 ,  	4 	, 4   , 0 ,BYTE_ORDER_MOT},
	{  StartReq,                                   RxBuffer_0x2C1 ,  	8 	, 1   , 0 ,BYTE_ORDER_MOT},
	{  KeyTypeInfo,                                RxBuffer_0x2C1 ,  	9	, 2   , 0 ,BYTE_ORDER_MOT},
	{  ExtTailSw,                                  RxBuffer_0x2C1 ,  	11	, 2   , 0 ,BYTE_ORDER_MOT},
	{  KeyIDInfo,                                  RxBuffer_0x2C1 ,  	13	, 3   , 0 ,BYTE_ORDER_MOT},
	{  StartWarn,                                  RxBuffer_0x2C1 ,  	16	, 1   , 0 ,BYTE_ORDER_MOT},
	{  RunStartWarn1,                              RxBuffer_0x2C1 ,  	17	, 1   , 0 ,BYTE_ORDER_MOT},
	{  RunStartWarn2,                              RxBuffer_0x2C1 ,  	18	, 1   , 0 ,BYTE_ORDER_MOT},
	{  PsgDoorCloseWarn,                           RxBuffer_0x2C1 ,  	19	, 1   , 0 ,BYTE_ORDER_MOT},
	{  DoorOpenWarn,                               RxBuffer_0x2C1 ,  	20	, 1   , 0 ,BYTE_ORDER_MOT},
	{  NoPWarn1,                                   RxBuffer_0x2C1 ,  	21	, 1   , 0 ,BYTE_ORDER_MOT},
	{  NoPWarn2,                                   RxBuffer_0x2C1 ,  	22	, 1   , 0 ,BYTE_ORDER_MOT},
	{  LockingWarn,                                RxBuffer_0x2C1 ,  	23	, 1   , 0 ,BYTE_ORDER_MOT},
	{  NotPressPedal,                              RxBuffer_0x2C1 ,  	25	, 2   , 0 ,BYTE_ORDER_MOT},
	{  GearWarnACCOff,                             RxBuffer_0x2C1 ,  	27	, 1   , 0 ,BYTE_ORDER_MOT},
	{  Remotelockkey_warn,                         RxBuffer_0x2C1 ,  	28	, 1   , 0 ,BYTE_ORDER_MOT},
	{  BatteryWarn,                                RxBuffer_0x2C1 ,  	29	, 1   , 0 ,BYTE_ORDER_MOT},
	{  GearWarnStart,                              RxBuffer_0x2C1 ,  	30	, 1   , 0 ,BYTE_ORDER_MOT},
	{  GearWarnDrvDoorOpen,                        RxBuffer_0x2C1 ,  	31	, 1   , 0 ,BYTE_ORDER_MOT},
	{  CreditLockStatus,                           RxBuffer_0x2C1 ,     32  , 1   , 0 ,BYTE_ORDER_MOT},
	{  PEPS_RemoteAuthstate,                       RxBuffer_0x2C1 ,  	40	, 2   , 0 ,BYTE_ORDER_MOT},
	{  PEPS_RemoteFeedback,                        RxBuffer_0x2C1 ,  	42	, 3   , 0 ,BYTE_ORDER_MOT},
	{  RemoteStartSts,                             RxBuffer_0x2C1 ,  	45	, 2   , 0 ,BYTE_ORDER_MOT},
	{  EngSwitchFail,                              RxBuffer_0x2C1 ,  	47	, 1   , 0 ,BYTE_ORDER_MOT},
	{  PEPS_MsgCounter,                            RxBuffer_0x2C1 ,  	48	, 4   , 0 ,BYTE_ORDER_MOT},
	{  RemoteCutPwrSts,                            RxBuffer_0x2C1 ,  	52	, 1   , 0 ,BYTE_ORDER_MOT},
	{  CurrUpgradeStaObt,                          RxBuffer_0x2C1 ,  	53	, 1   , 0 ,BYTE_ORDER_MOT},
	{  PEPS_MsgChecksum,                           RxBuffer_0x2C1 ,  	56	, 8   , 0 ,BYTE_ORDER_MOT},
	{  BCM_RemoteAuthChallenge0,                   RxBuffer_0x538 ,  	0 	, 8   , 0 ,BYTE_ORDER_MOT},
	{  BCM_RemoteAuthChallenge1,                   RxBuffer_0x538 ,  	8	, 8   , 0 ,BYTE_ORDER_MOT},
	{  BCM_RemoteAuthChallenge2,                   RxBuffer_0x538 ,  	16	, 8   , 0 ,BYTE_ORDER_MOT},
	{  BCM_RemoteAuthChallenge3,                   RxBuffer_0x538 ,  	24	, 8   , 0 ,BYTE_ORDER_MOT},
	{  BCM_RemoteAuthChallenge4,                   RxBuffer_0x538 ,  	32	, 8   , 0 ,BYTE_ORDER_MOT},
	{  BCM_RemoteAuthChallenge5,                   RxBuffer_0x538 ,  	40	, 8   , 0 ,BYTE_ORDER_MOT},
	{  BCM_RemoteAuthChallenge6,                   RxBuffer_0x538 ,  	48	, 8   , 0 ,BYTE_ORDER_MOT},
	{  BCM_RemoteAuthChallenge7,                   RxBuffer_0x538 ,  	56	, 8   , 0 ,BYTE_ORDER_MOT},
	{  BCM_TBOX_LearnKey0,                         RxBuffer_0x53A ,  	0 	, 8   , 0 ,BYTE_ORDER_MOT},
	{  BCM_TBOX_LearnKey1,                         RxBuffer_0x53A ,  	8	, 8   , 0 ,BYTE_ORDER_MOT},
	{  BCM_TBOX_LearnKey2,                         RxBuffer_0x53A ,  	16	, 8   , 0 ,BYTE_ORDER_MOT},
	{  BCM_TBOX_LearnKey3,                         RxBuffer_0x53A ,  	24	, 8   , 0 ,BYTE_ORDER_MOT},
	{  BCM_TBOX_LearnKey4,                         RxBuffer_0x53A ,  	32	, 8   , 0 ,BYTE_ORDER_MOT},
	{  BCM_TBOX_LearnKey5,                         RxBuffer_0x53A ,  	40	, 8   , 0 ,BYTE_ORDER_MOT},
	{  BCM_TBOX_LearnKey6,                         RxBuffer_0x53A ,  	48	, 8   , 0 ,BYTE_ORDER_MOT},
	{  BCM_TBOX_LearnKey7,                         RxBuffer_0x53A ,  	56	, 8   , 0 ,BYTE_ORDER_MOT},
    {  AirPurifMode,                               RxBuffer_0x5A1 ,     16  , 2   , 0 ,BYTE_ORDER_MOT},
    {  AirCleanerStS,                              RxBuffer_0x5A1 ,     19  , 1   , 0 ,BYTE_ORDER_MOT},
    {  ESCLSwselftestWarn,                         RxBuffer_0x2D1 ,     21  , 1   , 0 ,BYTE_ORDER_MOT},
    {  ESCLNoLockWarn,                             RxBuffer_0x2D1 ,     19  , 1   , 0 ,BYTE_ORDER_MOT},
    {  ESCLUnLockWarn,                             RxBuffer_0x2D1 ,     18  , 1   , 0 ,BYTE_ORDER_MOT},
    {  ESCL_Auth_Status,                           RxBuffer_0x2D1 ,     16  , 2   , 0 ,BYTE_ORDER_MOT},
    {  ESCL_Error    ,                             RxBuffer_0x2D1 ,     14  , 2   , 0 ,BYTE_ORDER_MOT},
    {  TBOX_BtAuthResponse0    ,                   TxBuffer_0x5A4 ,     0   , 8   , 0 ,BYTE_ORDER_MOT},
    {  TBOX_BtAuthResponse1    ,                   TxBuffer_0x5A4 ,     8   , 8   , 0 ,BYTE_ORDER_MOT},
    {  TBOX_BtAuthResponse2    ,                   TxBuffer_0x5A4 ,     16  , 8   , 0 ,BYTE_ORDER_MOT},
    {  TBOX_BtAuthResponse3    ,                   TxBuffer_0x5A4 ,     24  , 8   , 0 ,BYTE_ORDER_MOT},
    {  TBOX_BtAuthResponse4    ,                   TxBuffer_0x5A4 ,     32  , 8   , 0 ,BYTE_ORDER_MOT},
    {  TBOX_BtAuthResponse5    ,                   TxBuffer_0x5A4 ,     40  , 8   , 0 ,BYTE_ORDER_MOT},
    {  TBOX_BtAuthResponse6    ,                   TxBuffer_0x5A4 ,     48  , 8   , 0 ,BYTE_ORDER_MOT},
    {  TBOX_BtAuthResponse7    ,                   TxBuffer_0x5A4 ,     56  , 8   , 0 ,BYTE_ORDER_MOT},
    {  BCM_FL_Req    ,                             RxBuffer_0x5A3 ,     0   , 1   , 0 ,BYTE_ORDER_MOT},
    {  BCM_FR_Req    ,                             RxBuffer_0x5A3 ,     1   , 1   , 0 ,BYTE_ORDER_MOT},
    {  BCM_Trunk_Req    ,                          RxBuffer_0x5A3 ,     2   , 1   , 0 ,BYTE_ORDER_MOT},
    {  BCM_PS_Req    ,                             RxBuffer_0x5A3 ,     3   , 1   , 0 ,BYTE_ORDER_MOT},
    {  BCM_BtAuthChallenge0    ,                   RxBuffer_0x5A3 ,     56  , 56  , 0 ,BYTE_ORDER_MOT},
       

    {  Diag_Request,                               RxBuffer_0x777 ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
    {  Diag_FuncRequest,                           RxBuffer_0x7DF ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
    {  Diag_Response,                              TxBuffer_0x77F ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
    {  Diag_Request_0x7E0,                         RxBuffer_0x7E0 ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
    {  RTDiag_Response_0x7E8,                      RxBuffer_0x7E8 ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
    {  RTDiag_Request_0x7E0,                       TxBuffer_0x7E0 ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
    {  RTDiag_Request_0x7DF,                       TxBuffer_0x7DF ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
	{  RTDiag_Response_0x75D,                      RxBuffer_0x75D ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
    {  RTDiag_Request_0x755,                       TxBuffer_0x755 ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},

	{  RTDiag_Response_0x74B,                      RxBuffer_0x74B ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
    {  RTDiag_Request_0x743,                       TxBuffer_0x743 ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
	{  RTDiag_Response_0x758,                      RxBuffer_0x758 ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
    {  RTDiag_Request_0x750,                       TxBuffer_0x750 ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
	{  RTDiag_Response_0x759,                      RxBuffer_0x759 ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
    {  RTDiag_Request_0x751,                       TxBuffer_0x751 ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
	{  RTDiag_Response_0x75A,                      RxBuffer_0x75A ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
    {  RTDiag_Request_0x752,                       TxBuffer_0x752 ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
	{  RTDiag_Response_0x75C,                      RxBuffer_0x75C ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
    {  RTDiag_Request_0x754,                       TxBuffer_0x754 ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
	{  RTDiag_Response_0x75E,                      RxBuffer_0x75E ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
    {  RTDiag_Request_0x756,                       TxBuffer_0x756 ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
	{  RTDiag_Response_0x76D,                      RxBuffer_0x76D ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
    {  RTDiag_Request_0x765,                       TxBuffer_0x765 ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
	{  RTDiag_Response_0x76E,                      RxBuffer_0x76E ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
    {  RTDiag_Request_0x766,                       TxBuffer_0x766 ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
	{  RTDiag_Response_0x76F,                      RxBuffer_0x76F ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
    {  RTDiag_Request_0x767,                       TxBuffer_0x767 ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
	{  RTDiag_Response_0x778,                      RxBuffer_0x778 ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
    {  RTDiag_Request_0x770,                       TxBuffer_0x770 ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
	{  RTDiag_Response_0x779,                      RxBuffer_0x779 ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
    {  RTDiag_Request_0x771,                       TxBuffer_0x771 ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
	{  RTDiag_Response_0x77A,                      RxBuffer_0x77A ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
    {  RTDiag_Request_0x772,                       TxBuffer_0x772 ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
	{  RTDiag_Response_0x7E9,                      RxBuffer_0x7E9 ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
    {  RTDiag_Request_0x7E1,                       TxBuffer_0x7E1 ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},

	{  RTDiag_Response_0x78F,                      RxBuffer_0x78F ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
    {  RTDiag_Request_0x787,                       TxBuffer_0x787 ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
	{  RTDiag_Response_0x79A,                      RxBuffer_0x79A ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
    {  RTDiag_Request_0x792,                       TxBuffer_0x792 ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
	{  RTDiag_Response_0x7A8,                      RxBuffer_0x7A8 ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
    {  RTDiag_Request_0x7A0,                       TxBuffer_0x7A0 ,  	0	, 64   , 0 ,BYTE_ORDER_MOT},
};

